# Install additional libraries

In [1]:
%pip install IMDbPY

Requirement already satisfied: IMDbPY in c:\users\lenovo\miniconda3\lib\site-packages (2022.7.9)
Requirement already satisfied: cinemagoer in c:\users\lenovo\miniconda3\lib\site-packages (from IMDbPY) (2023.5.1)
Requirement already satisfied: SQLAlchemy in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (2.0.31)
Requirement already satisfied: lxml in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (4.6.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

# Import Libraries

In [1]:
# Data gathering libraries
from imdb import IMDb
import requests
import gzip as gz

In [2]:
# Data Analysis Libraries
import pandas as pd
import numpy as np

In [3]:
# Visualization libaries
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# NLP libraies
import nltk
from nltk.tokenize import word_tokenize
from gensim.corpora.dictionary import Dictionary
from gensim.models.tfidfmodel import TfidfModel
from gensim.similarities import MatrixSimilarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
# install punctuation tool kit
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [6]:
# additional libraries
import pprint
from tqdm import tqdm
import pickle as pkl
import warnings
warnings.filterwarnings('ignore')
import sys

# Data Handling

## Retriving Data from tmdb API

In [17]:
discover_urls = [f"https://api.themoviedb.org/3/discover/movie?include_adult=true&include_video=false&language=en-US&page={i}&sort_by=popularity.desc" for i in range(1,501)]

genre_url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

keyword_url = "https://api.themoviedb.org/3/movie/movie_id/keywords"

details_url = "https://api.themoviedb.org/3/movie/movie_id?language=en-US"

credit_url = "https://api.themoviedb.org/3/movie/movie_id/credits?language=en-US"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MDM0ZGRiZTc2MjBlNDA5YmIyZTFjYWY4YTQzM2JjOSIsInN1YiI6IjY0ZmY0NjA1ZWIxNGZhMDBhZGE1ZDU4ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jDadAw2N_wZERgQvHIqf-7XGKyORY1MQiw8DlIC09H8"
}

In [9]:
movies_results = []
for discover_url in tqdm(discover_urls):
    res = requests.get(discover_url, headers=headers)
    movies_results.extend(res.json()['results'])

100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [04:01<00:00,  2.07it/s]

In [10]:
genre_response = requests.get(genre_url,headers=headers)
genre_results = genre_response.json()['genres']

In [11]:
movies = {
    "id" : [],
    "title": [],
    "overview": [],
    "genres": [],
    "keywords":[],
    "release_date":[],
    "director": [],
    "director_popularity": [],
    "movie_popularity":[],
    "movie_imdb_id": []
}

In [12]:
for movie in tqdm(movies_results):
    movies['id'].append(movie['id'])
    movies['title'].append(movie['title'])
    movies['genres'].append(movie['genre_ids'])

100%|████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 535431.67it/s]

In [13]:
movies['keywords'] = []
for movie_id in tqdm(movies['id']):
    keyword_response = requests.get(url = keyword_url.replace("movie_id",str(movie_id)),
                                    headers = headers)
    keywords = keyword_response.json()['keywords']
    movie_keyword_names = []
    for keyword in keywords:
        movie_keyword_names.append(keyword['name'])
    movies['keywords'].append(movie_keyword_names)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [46:40<00:00,  3.57it/s]

In [14]:
movies['overview'] = []
movies['release_date'] = []
movies['movie_imdb_id'] = []
movies['movie_popularity'] = []
for movie_id in tqdm(movies['id']):
  details_response = requests.get(url = details_url.replace("movie_id",str(movie_id)),
                                  headers = headers)
  overview = details_response.json()['overview']
  release_date = details_response.json()['release_date']
  imdb_id = details_response.json()['imdb_id']
  popularity = details_response.json()['popularity']
  movies['overview'].append(overview)
  movies['release_date'].append(release_date)
  movies['movie_imdb_id'].append(imdb_id)
  movies['movie_popularity'].append(popularity)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [37:36<00:00,  4.43it/s]

In [16]:
movies['director'] = []
movies['director_popularity'] = []
for movie_id in tqdm(movies['id']):
  credit_response = requests.get(url = credit_url.replace("movie_id",str(movie_id)),
                                 headers = headers)
  crew = credit_response.json()['crew']
  director_names = []
  director_popularity = []
  for crew_credit in crew:
    if crew_credit['job'] == "Director":
      director_names.append(crew_credit['name'])
      director_popularity.append(crew_credit['popularity'])
  movies['director'].append(director_names)
  movies['director_popularity'].append(director_popularity)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [22:29<00:00,  7.41it/s]

In [17]:
for g_index in tqdm(range(len(movies['genres']))):
    for g_result in genre_results:
        movies['genres'][g_index] = (
            list(
            map(
                lambda x: str(x).replace(str(g_result['id']), g_result['name']),
                movies['genres'][g_index]
                )
            )
         )

100%|█████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 23324.38it/s]

In [18]:
for key,value in movies.items():
  print(key,'=>',len(value))

id => 10000
title => 10000
overview => 10000
genres => 10000
keywords => 10000
release_date => 10000
director => 10000
director_popularity => 10000
movie_popularity => 10000
movie_imdb_id => 10000

In [20]:
# movies.pop('movie_imdb_rating')
df_movies = pd.DataFrame(movies)

In [22]:
df_movies.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948

In [23]:
df_movies.to_json("movies_1.json")
# df_movies.T.to_json("movies_2.json")

In [7]:
# df_movies = pd.read_csv('movies.csv',lineterminator='\n').iloc[:,1:]
df_movies = pd.read_json('movies_1.json')

In [8]:
df_movies.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948

In [9]:
df_movies[df_movies['movie_imdb_id'].isnull()]

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
66,482600,Japanese Mom,"""Innocent face, D-cup breasts and perfect inte...","[Romance, Drama]",[softcore],2017-02-09,[Kim Moo-won],[2.911],213.021,None
78,1338575,M – La Última Esperanza,,"[Adventure, Drama, Science Fiction]",[],2023-01-04,[Vardan Tozija],[0.49],196.980,None
81,1190586,Leggings Mania,Jeong-hee was living with a man due to a de fa...,"[Drama, Romance]","[softcore, nudity]",2023-07-13,[Richard Kim],[7.877],197.521,None
155,1285810,Forbidden Immoral Sex 3: Too Young Stepmother,,[Drama],[stepmother],2018-05-07,[Sadao Sadaoka],[0.98],133.976,None
218,1149913,TOGEFILM - Mei Mei,,"[Drama, Romance]",[],2023-04-06,[],[],112.576,None
...,...,...,...,...,...,...,...,...,...,...
9793,1177963,No vayan!!: La película,This is the story of two inseparable cousins w...,"[Comedy, History, Family]",[],2023-11-23,[],[],15.525,None
9797,1336214,THE IMPACT | Groundbreaking Documentary,Discover the unsettling truths behind the worl...,"[Documentary, History, TV Movie, War]","[mind control, neo-nazism, society, totalitari...",2024-07-12,[],[],15.524,None
9815,1300527,Heavens,,"[Horror, Thriller]","[dream, nightmare, heavens]",2024-09-10,[Alberto Meleleo],[0.001],15.513,None
9820,1340881,"4EVE Concert ""NOW OR NEVER"" Live at Impact Arena",Thai pop superstars 4EVE dazzle their fans wit...,[Music],[],2024-08-30,[],[],15.507,None
9958,719128,Idol Sex: LA Korean Women,Typhoon and Taeyang brothers are sharing. The ...,"[Romance, Drama]","[softcore, erotic, melodrama]",2020-06-18,[Jeong Mi-na],[3.17],15.393,None

In [10]:
df_movies[df_movies['movie_imdb_id'] == '']

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
235,387824,Mom's Friend,"Seong Soo, a twenty years old boy, decided to ...","[Drama, Romance]",[softcore],2015-08-20,[Myeong Seok Hwan],[4.299],98.486,
432,60957,田中瞳 爆乳Jの衝撃,,[],[],2007-11-08,[],[],77.370,
2015,387822,Comic Series,Episode 1. Teasing the husband\r A man and a w...,"[Romance, Comedy]",[softcore],2016-02-25,[Ahn Il-hwan],[0.732],21.076,
2272,440617,Family Reconstruction,Gwang-sik is a single father with a son and Ha...,"[Romance, Drama]",[softcore],2017-02-14,[],[],32.675,
2575,452251,Beauty Salon: Special Service,A legendary beauty salon that is sure to becom...,"[Romance, Drama]","[sister, beauty salon, prostitution, threesome...",2016-12-29,[Lee Ri-dan],[7.557],30.680,
2935,405817,Young Mother: The Original,I had a dream...sleeping with you and Hwa-yeon...,"[Drama, Romance]","[softcore, complicated relationships]",2016-06-23,[Jeong Do-soo],[3.099],28.757,
3375,409276,What a Good Secretary Wants,The silent secret of the perfect woman. Geniu...,"[Romance, Drama]","[secretary, softcore]",2016-05-20,[Kim Hyo-jae],[1.079],26.908,
3708,431803,Kabaneri of the Iron Fortress: Life That Burns,"In the midst of an industrial revolution, the ...","[Animation, Drama, Action, Science Fiction]","[samurai, post-apocalyptic future, steampunk, ...",2017-01-07,[Tetsuro Araki],[4.471],25.700,
3761,397469,New Folder 2,"Ho-jae has the building, the house, the fancy ...",[Drama],[softcore],2015-10-23,[Hwang Sang-won],[1.772],25.509,
4006,15257,Hulk vs. Wolverine,Department H sends in Wolverine to track down ...,"[Animation, Action, Science Fiction, Adventure...","[superhero, mutant, based on comic, norse myth...",2009-01-27,[Frank Paur],[1.653],24.656,
4477,592742,Be My Master,"Meguro, who works for the advertising design c...",[Drama],[pink film],2018-09-29,[Hideo Jojo],[10.001],23.343,
4528,409387,Sex: A Relationship and Not Marriage,The life story of a woman who doesn't want to ...,"[Romance, Drama]",[softcore],2016-04-19,[Jo Kyeong-hoon-I],[0.9590000000000001],23.217,
6610,418827,Sister's Younger Husband,A sexy brother-in-law approached her? And he’s...,"[Comedy, Drama, Romance]","[softcore, complicated relationships]",2016-10-11,[Park Eun-ho],[0.366],19.074,
6799,357458,Young Mother: What's Wrong With My Age?,"Father, son and even grandson, are all mesmeri...","[Comedy, Romance]",[],2015-04-30,[Kim Jong-il],[1.278],18.800,
7748,376858,Boarding House 2,Joon-hyeok is preparing to pass the exam for 9...,[Romance],[softcore],2016-01-07,[Jeong Tae-ryeong],[0.741],17.559,
8166,460104,Young Lady,Joon-seok and Soo-yeon are 3 years married. Th...,"[Comedy, Drama, Romance]",[],2015-09-10,[Lee Se-jong],[0.001],17.112,
9779,101907,Hulk vs. Thor,"For ages, Odin has protected his kingdom of As...","[Action, Animation, Fantasy, Science Fiction]","[fight, superhero, based on comic, norse mytho...",2009-01-27,[Sam Liu],[3.341],15.537,
9801,117691,Gangs of Wasseypur - Part 1,"In 1970s India, Sardar Khan vows to take reven...","[Action, Thriller, Crime]","[mafia, gang, coal mining]",2012-06-22,[Anurag Kashyap],[10.461],15.522,

In [11]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   title                10000 non-null  object
 2   overview             10000 non-null  object
 3   genres               10000 non-null  object
 4   keywords             10000 non-null  object
 5   release_date         10000 non-null  object
 6   director             10000 non-null  object
 7   director_popularity  10000 non-null  object
 8   movie_popularity     10000 non-null  float64
 9   movie_imdb_id        9770 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 859.4+ KB

In [12]:
df_movies.drop(df_movies[(df_movies['movie_imdb_id'] == '') | (df_movies['movie_imdb_id'].isnull())].index,inplace=True)

In [13]:
df_movies.reset_index(inplace=True)
df_movies.drop(columns=['index'],inplace=True)

In [14]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   9752 non-null   int64
 1   title                9752 non-null   object
 2   overview             9752 non-null   object
 3   genres               9752 non-null   object
 4   keywords             9752 non-null   object
 5   release_date         9752 non-null   object
 6   director             9752 non-null   object
 7   director_popularity  9752 non-null   object
 8   movie_popularity     9752 non-null   float64
 9   movie_imdb_id        9752 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 762.0+ KB

## Filling missing Values

In [15]:
def get_director_name_and_popularity(id):
    if 'director' in (IMDb().get_movie(id).data.keys()):
        director_name = (IMDb()
                        .get_movie(id)
                        .data['director'][0]
                        .data['name']
        )
        url = ('https://api.themoviedb.org/3/search/person?query={}&include_adult=false&language=en-US&page=1'
                .format(director_name.strip().replace(" ","%20"))
              )

        results = (requests
                      .get(url,headers=headers)
                      .json()['results']
        )

        if len(results) > 0:
            popularity = results[0]['popularity']
        else:
            popularity = 0.0
            
    else:
          director_name = '-'
          popularity = 0.0
          
    return {'director_name':director_name,
                'director_popularity':popularity}

In [18]:
director_names = []
director_popularity = []
for index in tqdm(df_movies.index):
  if df_movies.iloc[index]['director'] == []:
    director_information = get_director_name_and_popularity(df_movies.iloc[index]['movie_imdb_id'][2:])
    director_names.append(director_information['director_name'])
    director_popularity.append(director_information['director_popularity'])
  else:
    director_names.append(df_movies.iloc[index]['director'])
    director_popularity.append(df_movies.iloc[index]['director_popularity'])

df_movies['director'] = director_names
df_movies['director_popularity'] = director_popularity

100%|█████████████████████████████████████████████████████████████████████████████| 9752/9752 [01:29<00:00, 108.38it/s]

## Integrate data from IMDb

In [19]:
Imdb = IMDb()

In [20]:
The_Nun_movie =Imdb.search_movie("Nun")[0]

In [21]:
Imdb.get_movie("5755238").data.keys()

dict_keys(['localized title', 'cast', 'genres', 'runtimes', 'countries', 'country codes', 'language codes', 'color info', 'aspect ratio', 'sound mix', 'certificates', 'original air date', 'rating', 'votes', 'cover url', 'imdbID', 'videos', 'plot outline', 'languages', 'title', 'year', 'kind', 'original title', 'director', 'writer', 'producer', 'composer', 'editor', 'editorial department', 'casting director', 'production design', 'art direction', 'production manager', 'art department', 'sound crew', 'special effects', 'visual effects', 'camera and electrical department', 'animation department', 'casting department', 'music department', 'miscellaneous crew', 'thanks', 'akas', 'production companies', 'distributors', 'other companies', 'plot', 'synopsis'])

In [22]:
ratings = pd.read_csv(gz.open("datasets/title.ratings.tsv.gz"),sep="\t")
ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2084
1  tt0000002            5.6       281
2  tt0000003            6.5      2086
3  tt0000004            5.4       182
4  tt0000005            6.2      2820

In [23]:
basics = pd.read_csv(gz.open("datasets/title.basics.tsv.gz"),delimiter='\t')

In [24]:
imdb_genres = basics.genres

In [25]:
basics.drop(columns=['genres'],inplace = True)

In [26]:
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,5
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1

In [ ]:
principals = pd.read_csv(gz.open("datasets/title.principals.tsv.gz"),sep='\t',encoding='utf-8',lineterminator='\n')

In [ ]:
principals.head()

In [27]:
df_1 = pd.merge(df_movies,ratings,how='inner',right_on='tconst',left_on = 'movie_imdb_id').drop(columns='tconst')

In [28]:
df_1.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709

In [29]:
df_2 = pd.merge(df_1,basics,how='inner',right_on='tconst',left_on='movie_imdb_id').drop(columns = ["tconst"])

In [30]:
df_2.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [31]:
sys.getsizeof(df_2)

13783197

In [32]:
df_2.to_csv('movies_df.csv')

# Dealing with DataBase

## Data Base API

## Inserting Data

## Retrieving Data

# Data Preprocessing

In [ ]:
movies_df_handling.info()

### Fix data types

In [ ]:
def converttypes(df,col,_type):
    if _type == 'int':
        df[col] = df[col].astype('int')

In [ ]:
movies_df_handling[movies_df_handling['endYear'] == '\\N']

# Data Analysis

# Visualization

# Building Models

 ## TF-IDF Model

## Jaccard Similarity Model