# Install additional libraries

In [1]:
%pip install IMDbPY

Requirement already satisfied: IMDbPY in c:\users\lenovo\miniconda3\lib\site-packages (2022.7.9)
Requirement already satisfied: cinemagoer in c:\users\lenovo\miniconda3\lib\site-packages (from IMDbPY) (2023.5.1)
Requirement already satisfied: SQLAlchemy in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (2.0.31)
Requirement already satisfied: lxml in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (4.6.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

# Import Libraries

In [1]:
# Data gathering libraries
from imdb import IMDb
import requests as req
import gzip as gz
import json

In [2]:
# Data Analysis Libraries
import pandas as pd
import numpy as np

In [3]:
# Visualization libaries
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# NLP libraies
import nltk
from nltk.tokenize import word_tokenize,RegexpTokenizer
import spacy
import fasttext as ft

In [5]:
# additional libraries
import pprint
from tqdm import tqdm
import pickle as pkl
import warnings
warnings.filterwarnings('ignore')
import sys
import time

# Data Gathering

## Retriving Data from tmdb API

In [6]:
discover_urls = [f"https://api.themoviedb.org/3/discover/tv?include_adult=false&include_video=false&language=en-US&page={i}" for i in range(1,501)]

urls = {
    'genre' : "https://api.themoviedb.org/3/genre/tv/list?language=en",
    
    'keyword': "https://api.themoviedb.org/3/tv/series_id/keywords",
    
    'external_ids' : "https://api.themoviedb.org/3/tv/series_id/external_ids",
    
    'details' : "https://api.themoviedb.org/3/tv/series_id?language=en-US",
    
    'credit' : "https://api.themoviedb.org/3/tv/series_id/credits?language=en-US"
}
headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MDM0ZGRiZTc2MjBlNDA5YmIyZTFjYWY4YTQzM2JjOSIsInN1YiI6IjY0ZmY0NjA1ZWIxNGZhMDBhZGE1ZDU4ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jDadAw2N_wZERgQvHIqf-7XGKyORY1MQiw8DlIC09H8"
}

In [7]:
tv_show_results = []
for discover_url in tqdm(discover_urls):
    res = req.get(discover_url, headers=headers)
    tv_show_results.extend(res.json()['results'])

100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [00:52<00:00,  9.55it/s]

In [8]:
genre_response = req.get(urls['genre'],headers=headers)
genre_results = genre_response.json()['genres']

In [9]:
tv_shows = {
    'id': [],
    'title': [],
    'overview':[], 
    'genres': [],
    'keywords': [],
    'first_air_date': [],
    'characters' : [],
    'popularity':[],
    'imdb_id':[],
}

In [10]:
for tv_show in tqdm(tv_show_results):
    tv_shows['id'].append(tv_show['id'])
    tv_shows['title'].append(tv_show['name'])
    tv_shows['genres'].append(tv_show['genre_ids'])
    tv_shows['overview'].append(tv_show['overview'])

100%|████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 814871.00it/s]

In [11]:
keys = list(tv_shows.keys())[4:]
for key in keys:
    tv_shows[key] = []

data = {}
for series_id in tqdm(tv_shows['id'],desc='tv'):
    
    for url in urls.keys():
        data[url] = req.get(url = urls[url].replace('series_id',str(series_id)),headers=headers).json()
    
    characters = []
    for cast_credit in data['credit']['cast']:
        characters.append(cast_credit['character'])

    keyword_names = []
    for keyword in data['keyword']['results']:
        keyword_names.append(keyword['name'])

    tv_shows['keywords'].append(keyword_names)
    for key in ['first_air_date','popularity']:
        tv_shows[key].append(data['details'][key])
    tv_shows['imdb_id'].append(data['external_ids']['imdb_id'])
    tv_shows['characters'].append(characters)

tv: 100%|██████████████████████████████████████████████████████████████████████| 10000/10000 [3:06:25<00:00,  1.12s/it]

In [38]:
tv_shows['keywords'] = []

In [39]:
tv_shows['keywords'] = []
for series_id in tqdm(tv_shows['id']):

SyntaxError: incomplete input (2820989078.py, line 3)

In [20]:
tv_shows['imdb_id'] = []
for series_id in tqdm(tv_shows['id']):
    
    imdb_id = external_data['imdb_id']
    tv_shows['imdb_id'].append(imdb_id)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [33:04<00:00,  5.04it/s]

In [21]:
tv_shows['characters'] = []
for series_id in tqdm(tv_shows['id']):
    credit_response = requests.get(url = credit_url.replace("series_id",str(series_id)),
                                 headers = headers)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [32:46<00:00,  5.09it/s]

In [12]:
for g_index in tqdm(range(len(tv_shows['genres']))):
    for g_result in genre_results:
        tv_shows['genres'][g_index] = (
            list(
            map(
                lambda x: str(x).replace(str(g_result['id']), g_result['name']),
                tv_shows['genres'][g_index]
                )
            )
         )

100%|█████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 17272.01it/s]

In [13]:
for key,value in tv_shows.items():
  print(key,'=>',len(value))

id => 10000
title => 10000
overview => 10000
genres => 10000
keywords => 10000
first_air_date => 10000
characters => 10000
popularity => 10000
imdb_id => 10000

## handling tdmb data

In [15]:
# tv_shows.pop('tv_show_imdb_rating')
df_tv_shows = pd.DataFrame(tv_shows)

In [1]:
# df_tv_shows.to_json('../datasets/tv_shows_1.json')
# df_tv_shows.T.to_json("tv_shows_2.json")

In [32]:
# df_tv_shows = pd.read_csv('tv_shows.csv',lineterminator='\n').iloc[:,1:]
df_tv_shows = pd.read_json('../datasets/json_files/tv_shows_1.json')

In [33]:
df_tv_shows.head(50)

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"[Drama, Family]","[ramayana, ramayan, shrimad ramayana]",2024-01-22,"[Vishnu / Ram, Laxmi / Sita, Raavan, Lakshman...",3216.286,tt30145246
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561
2,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,[Reality],"[competition, game show, housemates, reality c...",2005-08-21,"[Self - Host, Self - Host, Self - Host, Self -...",2456.098,tt0479336
3,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","[Action & Adventure, Sci-Fi & Fantasy, Drama]","[elves, dwarf, based on novel or book, prequel...",2022-09-01,"[Sauron / Annatar, Galadriel, Elrond, The Stra...",2311.669,tt7631058
4,122653,Gutfeld!,Greg Gutfeld examines the news of the day thro...,"[Comedy, Talk]",[],2021-04-05,"[Katherine Timpf, Greg Gutfeld]",2198.986,tt14401604
5,136166,Lang Leve de Liefde,,[Reality],"[romance, dating]",2020-01-20,[Self (Voice-over)],2084.677,tt15303180
6,242101,Cacau,"Cacau is an engaging saga of family secrets, c...",[Drama],[],2024-01-15,"[Clara ""Cacau"" Coutinho, Tiago Saavedra, Simon...",1951.255,tt28183323
7,242099,Senhora do Mar,,[Drama],[mar aberto],2024-02-05,"[Joana Gonçalves Pedrosa, Manuel Bettencourt, ...",1945.993,tt29625999
8,81329,Chronicles of the Sun,Claire is surprised when she gets arrested for...,[Soap],[],2018-08-27,"[Claire, Manu, Alice Bastide, Clément Becker, ...",1933.633,tt8883922
9,242931,Pulang Araw,Red Sun is a family drama that tells stories o...,"[Action & Adventure, Drama, War & Politics, Fa...","[world war ii, period drama, historical, histo...",2024-07-29,"[Eduardo dela Cruz, Teresita 'Morena' Borromeo...",1900.673,tt31381986
10,241492,Estrela da Casa,,[Reality],[],2024-08-13,[Self - Host],1862.078,tt29565262
11,243117,"Plus belle la vie, encore plus belle",,"[Soap, Drama]",[],2024-01-08,"[Thomas Marci, Mirta Torres, Blanche Marci, Lu...",1848.339,tt29694831
12,218145,Mom for rent,"Abandoned by his wife, Martin is lying to his ...","[Family, Comedy]",[],2023-01-09,"[Martin Toman, Nadežda „Nadi“ Vernerová, Hanka...",1763.787,tt26628159
13,112470,Ici tout commence,This television drama series is centered aroun...,"[Soap, Drama]",[],2020-11-02,"[Salomé Dekens, Anaïs Grimbert, Célia Gaissac,...",1744.910,tt13392064
14,237478,Mania de Você,,"[Soap, Drama, Mystery]","[telenovela, soap, novela]",2024-09-09,"[Viola, Luma, Mavi Salama, Rudá, Mércia, Isis,...",1689.418,tt29894090
15,61818,Late Night with Seth Meyers,"Seth Meyers, who is ""Saturday Night Live’s"" lo...","[Talk, Comedy]",[late-night show],2014-02-25,[Self - Host],1670.782,tt3513388
16,138501,Agatha All Along,Agatha Harkness gathers a coven of witches and...,"[Sci-Fi & Fantasy, Mystery, Comedy]","[witch, magic, based on comic, spin off, witch...",2024-09-18,"[Agnes O'Connor / Agatha Harkness, Teen, Jenni...",1660.332,tt15571732
17,247174,El Conde: Amor y Honor,A wrongful conviction changes the life of Alej...,[Drama],[],2024-07-01,"[Alejandro Gaitán / Conde, Mariana Zambrano, C...",1659.962,tt20601772
18,82708,The First Years,The First Years is a Dutch series for young pe...,"[Soap, Drama]","[high school, mockumentary, young adult]",2014-05-26,"[Yuna, Ryan, Amir, Jade, Ramses, Violet]",1656.425,tt4469214
19,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561
20,252373,A Promessa,,[Drama],[],2024-06-18,"[Verónica Rocha Morais, Laura Rocha, Olga, Bia...",1339.342,tt31860590
21,246331,Su Ji and U Ri,A healing romance begins between fallen star d...,"[Family, Drama]","[affectation, angry, familiar, hopeful, joyful]",2024-03-25,"[Jin Su-ji, Choi U-ri, Chae Sun-young, Jin Na-...",1314.974,tt31908553
22,122653,Gutfeld!,Greg Gutfeld examines the news of the day thro...,"[Comedy, Talk]",[],2021-04-05,"[Katherine Timpf, Greg Gutfeld]",2198.986,tt14401604
23,138501,Agatha All Along,Agatha Harkness gathers a coven of witches and...,"[Sci-Fi & Fantasy, Mystery, Comedy]","[witch, magic, based on comic, spin off, witch...",2024-09-18,"[Agnes O'Connor / Agatha Harkness, Teen, Jenni...",1660.332,tt15571732
24,206559,Binnelanders,A South African Afrikaans soap opera. It is se...,[Soap],"[afrikaans, hospital, soap, dramatic, drama]",2005-10-13,"[Dr. At Koster, Dr. Tertius Jonker, Dr. Conrad...",1226.378,tt1527854
25,18770,Gran Hermano,Gran Hermano is a reality television series br...,[Reality],[],2000-04-23,"[Presentador, Presentador Debates]",1197.195,tt0262163
26,72879,Tomorrow Is Ours,"The story revolves around the people of Sète, ...","[Crime, Drama]",[police officer],2017-07-17,"[Chloé Delcourt, Laurence, Alex Bertrand, Luci...",1174.016,tt7124904
27,206679,Na lovu,"Na Lovu is a Czech game-show, based on the lic...","[Reality, Family]","[game show, quiz]",2021-08-16,"[Kvízová dáma, Kalkulátor, Pan Lišák, Self - M...",1122.308,tt21340756
28,235484,Suidooster,Suidooster is a South African television soap ...,[Soap],[],2015-11-16,"[Sharleen (Mrs J) Jacobs, Lee-Ann Jacobs, Brid...",1101.493,tt5467444
29,207956,Alex Wagner Tonight,Alex Wagner brings years of reporting experien...,"[News, Talk]",[],2022-08-16,[],1056.138,tt21435480
30,239526,Sueños de libertad,,[Drama],"[period drama, 1950s, soap opera]",2024-02-25,"[, , , , , , , , , , , , , , , , , , , , ]",1026.258,tt30002038
31,237478,Mania de Você,,"[Soap, Drama, Mystery]","[telenovela, soap, novela]",2024-09-09,"[Viola, Luma, Mavi Salama, Rudá, Mércia, Isis,...",1689.418,tt29894090
32,4682,Strictly Come Dancing: It Takes Two,The companion show to the popular BBC One prog...,[],[],2004-10-25,"[Self - Presenter, Self - Presenter]",1007.032,tt0439401
33,24400,Deadly 60,Wildlife presenter Steve Backshall tracks down...,[Documentary],[],2009-05-28,[],1003.057,tt1692560
34,256121,Lavender Fields,Jasmin loved her idyllic life in her mountain ...,"[Drama, Action & Adventure]","[organized crime, soap opera, thriller, reveng...",2024-09-02,"[Lavender Fields / Jasmine Flores, Iris Buenav...",976.928,tt32537273
35,260196,La Isla: Desafío Extremo,A tour across Turkey where 24 contestants face...,[],[],2024-07-30,"[Conductor, Participante, Participante, Partic...",1088.425,tt32335076
36,207956,Alex Wagner Tonight,Alex Wagner brings years of reporting experien...,"[News, Talk]",[],2022-08-16,[],1056.138,tt21435480
37,2734,Law & Order: Special Victims Unit,"In the criminal justice system, sexually-based...","[Crime, Drama, Mystery]","[detective, sexual abuse, sex scandal, domesti...",1999-09-20,"[Olivia Benson, Odafin 'Fin' Tutuola, Dominick...",1042.910,tt0203259
38,194764,The Penguin,Witness the The Penguin's rise to power in Got...,"[Drama, Crime]","[based on comic, crime boss, miniseries, spin ...",2024-09-19,"[Oz 'The Penguin' Cobb, Sofia Falcone, Victor ...",1028.341,tt15435876
39,239526,Sueños de libertad,,[Drama],"[period drama, 1950s, soap opera]",2024-02-25,"[, , , , , , , , , , , , , , , , , , , , ]",1026.258,tt30002038
40,4682,Strictly Come Dancing: It Takes Two,The companion show to the popular BBC One prog...,[],[],2004-10-25,"[Self - Presenter, Self - Presenter]",1007.032,tt0439401
41,24400,Deadly 60,Wildlife presenter Steve Backshall tracks down...,[Documentary],[],2009-05-28,[],1003.057,tt1692560
42,256121,Lavender Fields,Jasmin loved her idyllic life in her mountain ...,"[Drama, Action & Adventure]","[organized crime, soap opera, thriller, reveng...",2024-09-02,"[Lavender Fields / Jasmine Flores, Iris Buenav...",976.928,tt32537273
43,32209,Al Fondo Hay Sitio,Al fondo hay sitio is a Peruvian TV series cre...,"[Comedy, Drama, Soap]","[family history, family holiday, family confli...",2009-03-30,"[Francesca Maldini, Rosario Flores, Don Gilber...",950.592,tt1441404
44,222289,Família é Tudo,"Five half-siblings – Venus, Andromeda, Jupiter...","[Comedy, Soap, Action & Adventure]","[romantic comedy, telenovela, absurd, amused, ...",2024-03-04,"[Frida / Catarina, Electra, Vênus, Tom, Andrôm...",949.532,tt29893924
45,2288,Prison Break,"Due to a political conspiracy, an innocent man...","[Action & Adventure, Crime, Drama]","[prison, prisoner, brother, conspiracy, escape...",2005-08-29,"[Michael Scofield, Lincoln Burrows, Sara Tancr...",916.822,tt0455275
46,63770,The Late Show with Stephen Colbert,Stephen Colbert brings his signature satire an...,"[Comedy, Talk]","[politcs, late-night show]",2015-09-08,[Self - Host],907.023,tt3697842
47,11890,"Goede Tijden, Slechte Tijden","Goede tijden, slechte tijden, also known as GT...",[Soap],[],1990-10-01,[],897.733,tt0096597
48,262364,Sjene prošlosti,,[Drama],[],2024-09-02,"[Marta, Paula, Ana, Šimun, Tomo, Mate, Eduard,...",887.951,tt33030426
49,14750,Na Wspólnej,Na Wspólnej is a Polish soap opera. It has bee...,[Soap],[],2003-01-27,"[Monika Cieślik, Maria Zięba, Włodzimierz Zięb...",817.586,tt0388626

In [34]:
df_tv_shows[df_tv_shows['imdb_id'].isnull()].shape[0]

0

In [35]:
df_tv_shows[df_tv_shows['imdb_id'] == ''].shape[0]

0

In [36]:
df_tv_shows.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8457 entries, 0 to 8456
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              8457 non-null   int64
 1   title           8457 non-null   object
 2   overview        8457 non-null   object
 3   genres          8457 non-null   object
 4   keywords        8457 non-null   object
 5   first_air_date  8457 non-null   object
 6   characters      8457 non-null   object
 7   popularity      8457 non-null   float64
 8   imdb_id         8457 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 660.7+ KB

In [37]:
df_tv_shows.drop(df_tv_shows[(df_tv_shows['imdb_id'] == '') | (df_tv_shows['imdb_id'].isnull())].index,inplace=True)

In [38]:
df_tv_shows.reset_index(inplace=True)
df_tv_shows.drop(columns=['index'],inplace=True)

In [39]:
df_tv_shows.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8457 entries, 0 to 8456
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              8457 non-null   int64
 1   title           8457 non-null   object
 2   overview        8457 non-null   object
 3   genres          8457 non-null   object
 4   keywords        8457 non-null   object
 5   first_air_date  8457 non-null   object
 6   characters      8457 non-null   object
 7   popularity      8457 non-null   float64
 8   imdb_id         8457 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 594.8+ KB

In [40]:
df_tv_shows.to_json("../datasets/tv_shows_1.json")

In [41]:
df_tv_shows = pd.read_json('../datasets/json_files/tv_shows_1.json')

## Integrate data from IMDb Bulk Dataset

In [42]:
ratings = pd.read_csv(gz.open("../datasets/zipfiles/title.ratings.tsv.gz"),sep="\t")
ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2084
1  tt0000002            5.6       281
2  tt0000003            6.5      2086
3  tt0000004            5.4       182
4  tt0000005            6.2      2820

In [43]:
basics = pd.read_csv(gz.open("../datasets/zipfiles/title.basics.tsv.gz"),delimiter='\t')

In [44]:
imdb_genres = basics.genres

In [45]:
basics.drop(columns=['genres'],inplace = True)

In [46]:
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,5
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1

In [47]:
basics.rename(columns={'genres': 'imdb_genres'},inplace = True)

In [48]:
# principals = pd.read_csv('../datasets/sv_files/imdb_characters_and_actor_ids.csv')

In [49]:
# principals.head()

,Unnamed: 0,id,imdb_id,type,ordering,nconst,category,characters
0,0,2,tt0094675,movie,1.0,nm0656999,actor,"[""Taisto Kasurinen""]"
1,1,2,tt0094675,movie,2.0,nm0352099,actress,"[""Irmeli""]"
2,2,2,tt0094675,movie,3.0,nm0671231,actor,"[""Mikkonen""]"
3,3,2,tt0094675,movie,4.0,nm0383990,actor,"[""Riku""]"
4,4,2,tt0094675,movie,5.0,nm0656998,actor,"[""Kaivosmies""]"

In [50]:
df_1 = pd.merge(df_tv_shows,ratings,how='inner',right_on='tconst',left_on = 'imdb_id').drop(columns='tconst')

In [51]:
df_1.head()

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"[Drama, Family]","[ramayana, ramayan, shrimad ramayana]",2024-01-22,"[Vishnu / Ram, Laxmi / Sita, Raavan, Lakshman...",3216.286,tt30145246,9.1,1580
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561,4.9,126
2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561,4.9,126
3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,[Reality],"[competition, game show, housemates, reality c...",2005-08-21,"[Self - Host, Self - Host, Self - Host, Self -...",2456.098,tt0479336,3.5,138
4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","[Action & Adventure, Sci-Fi & Fantasy, Drama]","[elves, dwarf, based on novel or book, prequel...",2022-09-01,"[Sauron / Annatar, Galadriel, Elrond, The Stra...",2311.669,tt7631058,6.9,376058

In [52]:
df_2 = pd.merge(df_1,basics,how='inner',right_on='tconst',left_on='imdb_id').drop(columns = ["tconst"])

In [53]:
df_2.head()

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"[Drama, Family]","[ramayana, ramayan, shrimad ramayana]",2024-01-22,"[Vishnu / Ram, Laxmi / Sita, Raavan, Lakshman...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N,\N
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,[Reality],"[competition, game show, housemates, reality c...",2005-08-21,"[Self - Host, Self - Host, Self - Host, Self -...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N,\N
4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","[Action & Adventure, Sci-Fi & Fantasy, Drama]","[elves, dwarf, based on novel or book, prequel...",2022-09-01,"[Sauron / Annatar, Galadriel, Elrond, The Stra...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,\N,60

In [54]:
sys.getsizeof(df_2)

11811972

In [61]:
principals.columns

Index(['Unnamed: 0', 'id', 'imdb_id', 'type', 'ordering', 'nconst', 'category',
       'characters'],
      dtype='object')

In [58]:
# df_3 = pd.merge(df_2,principals.drop(['Unnamed: 0','id','characters']),how='inner',on='imdb_id',)

In [60]:
# df_3.columns

Index(['id_x', 'title', 'overview', 'genres', 'keywords', 'first_air_date',
       'characters_x', 'popularity', 'imdb_id', 'averageRating', 'numVotes',
       'titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'Unnamed: 0', 'id_y', 'type', 'ordering',
       'nconst', 'category', 'characters_y'],
      dtype='object')

In [62]:
df_2.to_csv('../datasets/tv_shows_df.csv')

In [63]:
df_2

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"[Drama, Family]","[ramayana, ramayan, shrimad ramayana]",2024-01-22,"[Vishnu / Ram, Laxmi / Sita, Raavan, Lakshman...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N,\N
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,[Reality],[],2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,[Reality],"[competition, game show, housemates, reality c...",2005-08-21,"[Self - Host, Self - Host, Self - Host, Self -...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N,\N
4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","[Action & Adventure, Sci-Fi & Fantasy, Drama]","[elves, dwarf, based on novel or book, prequel...",2022-09-01,"[Sauron / Annatar, Galadriel, Elrond, The Stra...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,\N,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8108,44037,The Hollow Crown,A series of British television films featuring...,"[Drama, 36]",[period drama],2012-06-30,[],23.660,tt2262456,8.2,7436,tvSeries,The Hollow Crown,The Hollow Crown,0,2012,2016,150
8109,46619,Rectify,After 19 years on Death Row for the rape and m...,"[Crime, Drama]","[dna, georgia, death row, family relationships...",2013-04-22,"[Daniel Holden, Amantha Holden, Tawney Talbot,...",23.658,tt2183404,8.3,27876,tvSeries,Rectify,Rectify,0,2013,2016,60
8110,88233,The Defected,A thrilling story revolving around a policeman...,[Drama],[police],2019-04-01,"[Sheung Sing, Man Hei-wah, Bingo, Samuel Ching...",23.657,tt10141612,7.2,93,tvSeries,The Defected,Tie tan,0,2019,2019,\N
8111,62815,The Muppets,The Muppets return to primetime with a contemp...,"[Comedy, Family]","[behind the scenes, mockumentary]",2015-09-22,"[Kermit / Statler / Beaker / Rizzo (voice), Mi...",23.656,tt4651824,7.4,7396,tvSeries,The Muppets.,The Muppets.,0,2015,2016,21
8112,61408,Nagi-Asu: A Lull in the Sea,"Long ago, all humans lived beneath the sea. Ho...","[Animation, Drama, Sci-Fi & Fantasy]","[romance, middle school, based on manga, schoo...",2013-10-03,"[Hiradaira Chisaki (voice), Mukaido Manaka (vo...",23.650,tt3104236,7.3,1456,tvSeries,Nagi-Asu: A Lull in the Sea,Nagi no Asukara,0,2013,2014,23

# Dealing with DataBase

In [64]:
tv_shows_df = pd.read_csv('../datasets/tv_shows_df.csv')

In [65]:
tv_shows_df.head()

,Unnamed: 0,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"['Drama', 'Family']","['ramayana', 'ramayan', 'shrimad ramayana']",2024-01-22,"['Vishnu / Ram', 'Laxmi / Sita', 'Raavan', 'L...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N,\N
1,1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,['Reality'],[],2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
2,2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,['Reality'],[],2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
3,3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,['Reality'],"['competition', 'game show', 'housemates', 're...",2005-08-21,"['Self - Host', 'Self - Host', 'Self - Host', ...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N,\N
4,4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","['Action & Adventure', 'Sci-Fi & Fantasy', 'Dr...","['elves', 'dwarf', 'based on novel or book', '...",2022-09-01,"['Sauron / Annatar', 'Galadriel', 'Elrond', 'T...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,\N,60

In [66]:
tv_shows_df['genres'].iloc[1]

"['Reality']"

In [67]:
type(tv_shows_df['genres'].iloc[1]), type(tv_shows_df['keywords'].iloc[1])

(str, str)

In [68]:
for col in ['genres','keywords']:
    tv_shows_df[col] = tv_shows_df[col].replace('\]|\[|\'|\"','',regex=True)

In [69]:
tv_shows_df.head()

,Unnamed: 0,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"Drama, Family","ramayana, ramayan, shrimad ramayana",2024-01-22,"['Vishnu / Ram', 'Laxmi / Sita', 'Raavan', 'L...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N,\N
1,1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
2,2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,\N
3,3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,Reality,"competition, game show, housemates, reality co...",2005-08-21,"['Self - Host', 'Self - Host', 'Self - Host', ...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N,\N
4,4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","Action & Adventure, Sci-Fi & Fantasy, Drama","elves, dwarf, based on novel or book, prequel,...",2022-09-01,"['Sauron / Annatar', 'Galadriel', 'Elrond', 'T...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,\N,60

In [73]:
# tv_shows_df.drop(['endYear','Unnamed: 0'],axis = 1, inplace = True)
# tv_shows_df.drop(['Unnamed: 0.1'],axis = 1)

In [74]:
tv_shows_df.head()

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,"Drama, Family","ramayana, ramayan, shrimad ramayana",2024-01-22,"['Vishnu / Ram', 'Laxmi / Sita', 'Raavan', 'L...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,Reality,"competition, game show, housemates, reality co...",2005-08-21,"['Self - Host', 'Self - Host', 'Self - Host', ...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N
4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...","Action & Adventure, Sci-Fi & Fantasy, Drama","elves, dwarf, based on novel or book, prequel,...",2022-09-01,"['Sauron / Annatar', 'Galadriel', 'Elrond', 'T...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,60

In [75]:
for col in ['genres','keywords']:
    tv_shows_df[col] = tv_shows_df[col].apply(lambda x: x.split(', '))
    tv_shows_df[col] = tv_shows_df[col].apply(lambda x: ' '.join([i.strip().replace(' ','-') for i in x]))

In [76]:
tv_shows_df.overview.fillna('-',inplace=True)

In [79]:
tv_shows_df.iloc[8].overview

'Cacau is an engaging saga of family secrets, clandestine loves and sacrifices, all sweetened by the irresistible taste of chocolate and the magic of cocoa plantations.'

In [80]:
overviews = []
for i in range(tv_shows_df.shape[0]):
    record = tv_shows_df.iloc[i]
    if record.overview == '-':
        overviews.append(record.title)
    else:
        overviews.append(record.overview)
tv_shows_df.overview = overviews

In [121]:
# tv_shows_df.drop('release_date',axis = 1,inplace = True)

In [83]:
tv_shows_df.head()

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,Drama Family,ramayana ramayan shrimad-ramayana,2024-01-22,"['Vishnu / Ram', 'Laxmi / Sita', 'Raavan', 'L...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,Reality,competition game-show housemates reality-compe...,2005-08-21,"['Self - Host', 'Self - Host', 'Self - Host', ...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N
4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...",Action-&-Adventure Sci-Fi-&-Fantasy Drama,elves dwarf based-on-novel-or-book prequel bat...,2022-09-01,"['Sauron / Annatar', 'Galadriel', 'Elrond', 'T...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,60

In [85]:
tv_shows_df.drop('characters',axis = 1)

,id,title,overview,genres,keywords,first_air_date,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,Drama Family,ramayana ramayan shrimad-ramayana,2024-01-22,3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,Reality,competition game-show housemates reality-compe...,2005-08-21,2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N
4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...",Action-&-Adventure Sci-Fi-&-Fantasy Drama,elves dwarf based-on-novel-or-book prequel bat...,2022-09-01,2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8108,44037,The Hollow Crown,A series of British television films featuring...,Drama 36,period-drama,2012-06-30,23.660,tt2262456,8.2,7436,tvSeries,The Hollow Crown,The Hollow Crown,0,2012,150
8109,46619,Rectify,After 19 years on Death Row for the rape and m...,Crime Drama,dna georgia death-row family-relationships tra...,2013-04-22,23.658,tt2183404,8.3,27876,tvSeries,Rectify,Rectify,0,2013,60
8110,88233,The Defected,A thrilling story revolving around a policeman...,Drama,police,2019-04-01,23.657,tt10141612,7.2,93,tvSeries,The Defected,Tie tan,0,2019,\N
8111,62815,The Muppets,The Muppets return to primetime with a contemp...,Comedy Family,behind-the-scenes mockumentary,2015-09-22,23.656,tt4651824,7.4,7396,tvSeries,The Muppets.,The Muppets.,0,2015,21
8112,61408,Nagi-Asu: A Lull in the Sea,"Long ago, all humans lived beneath the sea. Ho...",Animation Drama Sci-Fi-&-Fantasy,romance middle-school based-on-manga school-li...,2013-10-03,23.650,tt3104236,7.3,1456,tvSeries,Nagi-Asu: A Lull in the Sea,Nagi no Asukara,0,2013,23

In [86]:
tv_shows_df.to_csv('../datasets/sv_files/tv_shows_df_edited.csv')

In [393]:
requests.delete('http://localhost:8080/delete')

## Inserting Data

In [151]:
tv_shows_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7825 entries, 0 to 7824
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7825 non-null   int64
 1   title                7825 non-null   object
 2   overview             7825 non-null   object
 3   genres               7825 non-null   object
 4   keywords             7825 non-null   object
 5   tv_show_popularity   7825 non-null   float64
 6   tv_show_imdb_id      7825 non-null   object
 7   tv_show_imdb_rating  7825 non-null   float64
 8   num_votes            7825 non-null   int64
 9   title_type           7825 non-null   object
 10  primary_title        7825 non-null   object
 11  original_title       7825 non-null   object
 12  is_adult             7825 non-null   int64
 13  start_year           7825 non-null   int64
 14  end_year             7825 non-null   object
 15  runtime_minutes      7825 non-null   int32
dtypes: float64(2), int32(1), int64(4), object(9)
memory usage: 947.7+ KB

In [106]:
tv_shows_df['runtimeMinutes'].replace({'\\N':0},inplace=True)

In [107]:
tv_shows_df['runtimeMinutes'] = tv_shows_df['runtimeMinutes'].astype(int)

In [108]:
tv_shows_df.rename(columns=
    {
        "averageRating": "tv_show_imdb_rating",
        "numVotes":"num_votes",
        "titleType": "title_type",
        "primaryTitle": "primary_title",
        "originalTitle": "original_title",
        "isAdult":"is_adult",
        "startYear":"start_year",
        "endYear":"end_year",
        "runtimeMinutes": "runtime_minutes"
    }
,inplace=True)

In [398]:
tv_shows_documents = tv_shows_df.drop(columns = ['title_type','primary_title','original_title','is_adult','end_year']).T.to_dict()

In [399]:
first_it = tv_shows_documents[0]

In [400]:
first_it

{'id': 365177,
 'title': 'Borderlands',
 'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
 'genres': ['Action',
  ' Science Fiction',
  ' Comedy',
  ' Adventure',
  ' Thriller'],
 'keywords': ['outlaw',
  ' based on video game',
  ' unlikely friendship',
  ' talking robot',
  ' missing girl',
  ' band of misfits',
  ' mysterious power'],
 'release_date': '2024-08-07',
 'director': ['Eli Roth'],
 'director_popularity': ['24.36'],
 'movie_popularity': 2388.352,
 'movie_imdb_id': 'tt4978420',
 'movie_imdb_rating': 4.5,
 'num_votes': 23064,
 'runtime_minutes': 101}

In [401]:
for key in first_it.keys():
    print(key,'->',type(first_it[key]))

id -> <class 'int'>
title -> <class 'str'>
overview -> <class 'str'>
genres -> <class 'list'>
keywords -> <class 'list'>
release_date -> <class 'str'>
director -> <class 'list'>
director_popularity -> <class 'list'>
movie_popularity -> <class 'float'>
movie_imdb_id -> <class 'str'>
movie_imdb_rating -> <class 'float'>
num_votes -> <class 'int'>
runtime_minutes -> <class 'int'>

In [402]:
# id: int
# title: str
# overview:str 
# genres: list
# keywords: list
# release_date: str
# director: list
# director_popularity:list
# tv_show_popularity:float
# tv_show_imdb_id:str 
# tv_show_imdb_rating:float
# runtime_minutes:int

In [403]:
tv_show_docs = list(tv_shows_documents.values())

In [404]:
tv_show_docs[:4]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'num_votes': 23064,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'num_votes': 275259,
  'runtime_minutes': 128},
 {'id': 917496,
  'title': 'Beetlejuice Beetlejuice',
  'overview': "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
  'genres': ['Comedy', ' Horror', ' Fantasy'],
  'keywords': ['afterlife',
   ' haunted house',
   ' sequel',
   ' paranormal',
   ' teenage girl',
   ' gothic',
   ' death',
   ' new england',
   ' ghost',
   ' horror comedy',
   ' unexpected death',
   ' mother daughter relationship',
   ' fantasy',
   ' fantasy comedy'],
  'release_date': '2024-09-04',
  'director': ['Tim Burton'],
  'director_popularity': ['33.964'],
  'movie_popularity': 1567.733,
  'movie_imdb_id': 'tt2049403',
  'movie_imdb_rating': 7.1,
  'num_votes': 25446,
  'runtime_minutes': 105},
 {'id': 1022789,
  'title': 'Inside Out 2',
  'overview': "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  'genres': ['Animation', ' Family', ' Adventure', ' Comedy'],
  'keywords': ['sadness',
   ' disgust',
   ' sequel',
   ' computer animation',
   ' teenage girl',
   ' fear',
   ' anger',
   ' envy',
   ' aftercreditsstinger',
   ' duringcreditsstinger',
   ' emotions',
   ' embarrasment',
   ' anxious',
   ' joy',
   ' anxiety',
   ' frustrated'],
  'release_date': '2024-06-11',
  'director': ['Kelsey Mann'],
  'director_popularity': ['13.717'],
  'movie_popularity': 1485.085,
  'movie_imdb_id': 'tt22022452',
  'movie_imdb_rating': 7.7,
  'num_votes': 126369,
  'runtime_minutes': 96}]

In [405]:
res.json()

{'acknowledged': True,

In [373]:
tv_shows_docs = json.dumps(tv_show_docs)

In [374]:
tv_shows_data = json.loads(tv_shows_docs)

In [375]:
type(tv_shows_data)

list

In [376]:
tv_shows_data[:2]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'num_votes': 23064,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'num_votes': 275259,
  'runtime_minutes': 128}]

In [299]:
mov_df = pd.DataFrame().from_dict(tv_shows_data)

In [407]:
mov_df.isnull().sum()

id                     0
title                  0
overview               0
genres                 0
keywords               0
release_date           0
director               0
director_popularity    0
movie_popularity       0
movie_imdb_id          0
movie_imdb_rating      0
num_votes              0
runtime_minutes        0
dtype: int64

In [408]:
tv_shows_data = list(mov_df.T.to_dict().values())

In [409]:
tv_shows_data[:5]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'num_votes': 23064,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'num_votes': 275259,
  'runtime_minutes': 128},
 {'id': 917496,
  'title': 'Beetlejuice Beetlejuice',
  'overview': "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
  'genres': ['Comedy', ' Horror', ' Fantasy'],
  'keywords': ['afterlife',
   ' haunted house',
   ' sequel',
   ' paranormal',
   ' teenage girl',
   ' gothic',
   ' death',
   ' new england',
   ' ghost',
   ' horror comedy',
   ' unexpected death',
   ' mother daughter relationship',
   ' fantasy',
   ' fantasy comedy'],
  'release_date': '2024-09-04',
  'director': ['Tim Burton'],
  'director_popularity': ['33.964'],
  'movie_popularity': 1567.733,
  'movie_imdb_id': 'tt2049403',
  'movie_imdb_rating': 7.1,
  'num_votes': 25446,
  'runtime_minutes': 105},
 {'id': 1022789,
  'title': 'Inside Out 2',
  'overview': "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  'genres': ['Animation', ' Family', ' Adventure', ' Comedy'],
  'keywords': ['sadness',
   ' disgust',
   ' sequel',
   ' computer animation',
   ' teenage girl',
   ' fear',
   ' anger',
   ' envy',
   ' aftercreditsstinger',
   ' duringcreditsstinger',
   ' emotions',
   ' embarrasment',
   ' anxious',
   ' joy',
   ' anxiety',
   ' frustrated'],
  'release_date': '2024-06-11',
  'director': ['Kelsey Mann'],
  'director_popularity': ['13.717'],
  'movie_popularity': 1485.085,
  'movie_imdb_id': 'tt22022452',
  'movie_imdb_rating': 7.7,
  'num_votes': 126369,
  'runtime_minutes': 96},
 {'id': 970347,
  'title': 'The Killer',
  'overview': 'Zee is a feared contract killer known as "the Queen of the Dead," but when she refuses to murder a young blind woman, she finds herself hunted both by criminal colleagues and a determined police detective.',
  'genres': ['Action', ' Thriller', ' Crime'],
  'keywords': [''],
  'release_date': '2024-08-22',
  'director': ['John Woo'],
  'director_popularity': ['16.765'],
  'movie_popularity': 1084.443,
  'movie_imdb_id': 'tt1121948',
  'movie_imdb_rating': 5.7,
  'num_votes': 6709,
  'runtime_minutes': 126}]

In [410]:
res = requests.post(url='http://localhost:8080/post/data',json={'tv_shows':tv_shows_data})

In [411]:
res.json()

{'acknowledged': True,

## Retrieving Data

In [421]:
res = requests.get(url='http://localhost:8080/get/all')

In [422]:
res.status_code

200

In [423]:
res.json()[0].keys()

dict_keys(['id', 'title', 'overview', 'genres', 'keywords', 'release_date', 'director', 'director_popularity', 'movie_popularity', 'movie_imdb_id', 'movie_imdb_rating', 'num_votes', 'runtime_minutes'])

In [424]:
df = pd.DataFrame().from_dict(res.json())

# Data Preprocessing

In [87]:
df = pd.read_csv('../datasets/sv_files/tv_shows_df_edited.csv')

In [88]:
df.head()

,Unnamed: 0,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes
0,0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,Drama Family,ramayana ramayan shrimad-ramayana,2024-01-22,"['Vishnu / Ram', 'Laxmi / Sita', 'Raavan', 'L...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N
1,1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,NaN,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
2,2,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,NaN,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N
3,3,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,Reality,competition game-show housemates reality-compe...,2005-08-21,"['Self - Host', 'Self - Host', 'Self - Host', ...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N
4,4,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...",Action-&-Adventure Sci-Fi-&-Fantasy Drama,elves dwarf based-on-novel-or-book prequel bat...,2022-09-01,"['Sauron / Annatar', 'Galadriel', 'Elrond', 'T...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,60

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8113 entries, 0 to 8112
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      8113 non-null   int64
 1   id              8113 non-null   int64
 2   title           8113 non-null   object
 3   overview        8113 non-null   object
 4   genres          7921 non-null   object
 5   keywords        6213 non-null   object
 6   first_air_date  8098 non-null   object
 7   characters      8113 non-null   object
 8   popularity      8113 non-null   float64
 9   imdb_id         8113 non-null   object
 10  averageRating   8113 non-null   float64
 11  numVotes        8113 non-null   int64
 12  titleType       8113 non-null   object
 13  primaryTitle    8113 non-null   object
 14  originalTitle   8113 non-null   object
 15  isAdult         8113 non-null   int64
 16  startYear       8113 non-null   int64
 17  runtimeMinutes  8113 non-null   object
dtypes: float64(2), int64(5), object(11)
memory usage: 1.1+ MB

In [92]:
# df['release_date'].replace({'-':np.nan},inplace=True)

In [93]:
# df['startYear'] = pd.to_datetime(df['release_date']).dt.year

In [8]:
tokenizer = RegexpTokenizer(r'\w+')

In [9]:
with open('../datasets/stopwords.txt','r') as stopfp:
    stop_words = stopfp.readlines()

In [10]:
stop_words = stop_words[0].replace('"','').split(', ')

> #### after downloading it from `> spacy download en_core_web_lg` command

In [11]:
df = df[~df['imdb_id'].duplicated()].reset_index().drop(columns = 'index')

In [12]:
df.genres.replace(np.nan,'',inplace=True)

In [13]:
# genres tags
genre_tags = df['genres'].str.lower().to_list()#.apply(lambda x: ' '.join([i.strip().replace(' ','-') for i in x]).strip().lower()).to_list()

In [14]:
genre_tags[:5]

['drama family',
 'reality',
 'reality',
 'action-&-adventure sci-fi-&-fantasy drama',
 'comedy talk']

In [15]:
df['keywords'].replace(np.nan,'',inplace = True)

In [16]:
# keywords tags 
keyword_tags = df['keywords'].to_list()#.apply(lambda x: ' '.join([i.strip().replace(' ','-') for i in x]).strip().lower()).to_list()

In [17]:
keyword_tags[:5]

['ramayana ramayan shrimad-ramayana',
 '',
 'competition game-show housemates reality-competition big-brother',
 'elves dwarf based-on-novel-or-book prequel battle fantasy-world mysterious-stranger franchise high-fantasy sword-and-sorcery creatures strong-female-protagonist epic-quest trolls harfoots',
 '']

In [18]:
overviews = df['overview']

In [19]:
# overview tags
overview_tags = []
for overview in tqdm(overviews):
    tags = []
    new_overview = ' '.join(set(tokenizer.tokenize(overview.lower())))
    word_token = word_tokenize(new_overview)
    for w in word_token:
        if (w.lower() not in stop_words):
            tags.append(w.replace(' ','-'))
    overview_tags.append(' '.join(tags).lower())

100%|████████████████████████████████████████████████████████████████████████████| 6283/6283 [00:04<00:00, 1430.10it/s]

In [20]:
overview_tags[:6]

['shrimad television series cultural deep ramayan reverence ambitious epic timeless contemporary sensibility brings commitment life authenticity',
 'couto website chance claim months round celebrity grand owned farm season reality directed current weekly hours carelli swedish endemol alongside channel presented privacy actress pay day celebrities chris living sony television series news brazilian entertainment 2001 clock version steps junior offer produced created isolated prize remains coverage avoiding group rodrigo originally strix fazenda view record based win cameras eviction compete contestants reporter britto association',
 'relationships eventually adaptation winner big tasks challenges supervised housemates game filipino program live week share philippine brother features stories reality evicted build decides nomination public meaningful',
 'characters ensemble mountains númenor evil reaches time darkest cast breathtaking depths furthest live peace majestic kingdoms long legacies emergence confront kingdom earth island relative lindon misty follow forests carve map middle',
 'culture fused pop greg news gutfeld day satiric lens examines',
 'leve liefde lang']

In [21]:
df.columns

Index(['Unnamed: 0', 'id', 'title', 'overview', 'genres', 'keywords',
       'first_air_date', 'characters', 'popularity', 'imdb_id',
       'averageRating', 'numVotes', 'titleType', 'primaryTitle',
       'originalTitle', 'isAdult', 'startYear', 'runtimeMinutes', 'tags'],
      dtype='object')

In [22]:
tags = []
for i in tqdm(df.index):
    tag = (
        str(genre_tags[i]).lower() + ' ' +
        str(keyword_tags[i]).lower() + ' ' +
        str(overview_tags[i]).lower()
    )
    ' '.join(list(set(tag.split(' '))))
    tags.append(tag)

100%|██████████████████████████████████████████████████████████████████████████| 6283/6283 [00:00<00:00, 134166.99it/s]

In [23]:
import sys
sys.getsizeof(tags)

53080

In [24]:
df['tags'] = tags

In [25]:
sys.getsizeof(df['tags'])

1973948

In [26]:
# requests.delete(url='http://localhost:8080/delete')

In [27]:
df.drop('Unnamed: 0',axis = 1,inplace=True)

In [28]:
data = list(df.T.to_dict().values())

In [136]:
# res = requests.post(url='http://localhost:8080/post/data',json={'tv_shows':data})

In [29]:
df.isnull().sum()

id                 0
title              0
overview           0
genres             0
keywords           0
first_air_date    12
characters         0
popularity         0
imdb_id            0
averageRating      0
numVotes           0
titleType          0
primaryTitle       0
originalTitle      0
isAdult            0
startYear          0
runtimeMinutes     0
tags               0
dtype: int64

In [30]:
df.query(f"imdb_id == 'tt0903747'")

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes,tags
67,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",Drama Crime,new-mexico drug-dealer narcissism psychopath t...,2008-01-20,"['Walter White', 'Jesse Pinkman', 'Skyler Whit...",469.533,tt0903747,9.5,2202516,tvSeries,Breaking Bad,Breaking Bad,0,2008,45,drama crime new-mexico drug-dealer narcissism ...

In [31]:
df.sort_values(by='popularity',ascending=False).head(20)

,id,title,overview,genres,keywords,first_air_date,characters,popularity,imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes,tags
0,242722,Shrimad Ramayan,Shrimad Ramayan is an ambitious television ser...,Drama Family,ramayana ramayan shrimad-ramayana,2024-01-22,"['Vishnu / Ram', 'Laxmi / Sita', 'Raavan', 'L...",3216.286,tt30145246,9.1,1580,tvSeries,Shrimad Ramayan,Shrimad Ramayan,0,2024,\N,drama family ramayana ramayan shrimad-ramayana...
1,31342,A Fazenda,A Fazenda is the current Brazilian version of ...,Reality,,2009-05-31,[],2661.898,tt1842561,4.9,126,tvSeries,A Fazenda,A Fazenda,0,2009,\N,reality couto website chance claim months rou...
2,8892,Pinoy Big Brother,The Philippine adaptation of the reality game ...,Reality,competition game-show housemates reality-compe...,2005-08-21,"['Self - Host', 'Self - Host', 'Self - Host', ...",2456.098,tt0479336,3.5,138,tvSeries,Pinoy Big Brother,Pinoy Big Brother,0,2005,\N,reality competition game-show housemates reali...
3,84773,The Lord of the Rings: The Rings of Power,"Beginning in a time of relative peace, we foll...",Action-&-Adventure Sci-Fi-&-Fantasy Drama,elves dwarf based-on-novel-or-book prequel bat...,2022-09-01,"['Sauron / Annatar', 'Galadriel', 'Elrond', 'T...",2311.669,tt7631058,6.9,376058,tvSeries,The Lord of the Rings: The Rings of Power,The Lord of the Rings: The Rings of Power,0,2022,60,action-&-adventure sci-fi-&-fantasy drama elve...
4,122653,Gutfeld!,Greg Gutfeld examines the news of the day thro...,Comedy Talk,,2021-04-05,"['Katherine Timpf', 'Greg Gutfeld']",2198.986,tt14401604,6.1,1649,tvSeries,Gutfeld!,Gutfeld!,0,2021,60,comedy talk culture fused pop greg news gutfe...
5,136166,Lang Leve de Liefde,Lang Leve de Liefde,Reality,romance dating,2020-01-20,['Self (Voice-over)'],2084.677,tt15303180,6.8,21,tvSeries,Lang leve de liefde,Lang leve de liefde,0,2020,\N,reality romance dating leve liefde lang
6,242101,Cacau,"Cacau is an engaging saga of family secrets, c...",Drama,,2024-01-15,"['Clara ""Cacau"" Coutinho', 'Tiago Saavedra', '...",1951.255,tt28183323,6.6,40,tvSeries,Cacau,Cacau,0,2024,\N,drama saga engaging loves magic secrets cocoa...
7,242099,Senhora do Mar,Senhora do Mar,Drama,mar-aberto,2024-02-05,"['Joana Gonçalves Pedrosa', 'Manuel Bettencour...",1945.993,tt29625999,7.2,33,tvSeries,Senhora do Mar,Senhora do Mar,0,2024,\N,drama mar-aberto senhora mar
8,81329,Chronicles of the Sun,Claire is surprised when she gets arrested for...,Soap,,2018-08-27,"['Claire', 'Manu', 'Alice Bastide', 'Clément B...",1933.633,tt8883922,5.8,108,tvSeries,Chronicles of the Sun,Un si grand soleil,0,2018,26,soap friend arrested returns montpellier chil...
9,242931,Pulang Araw,Red Sun is a family drama that tells stories o...,Action-&-Adventure Drama War-&-Politics Family,world-war-ii period-drama historical historica...,2024-07-29,"['Eduardo dela Cruz', ""Teresita 'Morena' Borro...",1900.673,tt31381986,9.2,80,tvSeries,Red Sun,Pulang araw,0,2024,\N,action-&-adventure drama war-&-politics family...
10,243117,"Plus belle la vie, encore plus belle","Plus belle la vie, encore plus belle",Soap Drama,,2024-01-08,"['Thomas Marci', 'Mirta Torres', 'Blanche Marc...",1848.339,tt29694831,7.3,16,tvSeries,"Plus belle la vie, encore plus belle","Plus belle la vie, encore plus belle",0,2024,20,soap drama belle vie encore
11,218145,Mom for rent,"Abandoned by his wife, Martin is lying to his ...",Family Comedy,,2023-01-09,"['Martin Toman', 'Nadežda „Nadi“ Vernerová', '...",1763.787,tt26628159,4.3,22,tvSeries,Mama na prenájom,Mama na prenájom,0,2023,\N,family comedy martin hanka lies daughter comp...
12,112470,Ici tout commence,This television drama series is centered aroun...,Soap Drama,,2020-11-02,"['Salomé Dekens', 'Anaïs Grimbert', 'Célia Gai...",1744.910,tt13392064,7.0,99,tvSeries,Ici tout commence,Ici tout commence,0,2020,\N,soap drama renowned relationships complex tel...
13,61818,Late Night with Seth Meyers,"Seth Meyers, who is ""Saturday Night Live’s"" lo...",Talk Comedy,late-night-show,2014-02-25,['Self - Host'],1670.782,tt3513388,6.3,8030,tvSeries,Late Night with Seth Meyers,Late Night with Seth Meyers,0,2014,60,talk comedy late-night-show popular sharp nbc ...
14,247174,El Conde: Amor y Honor,A wrongful conviction changes the life of Alej...,Drama,,2024-07-01,"['Alejandro Gaitán / Conde', 'Mariana Zambrano...",1659.962,tt20601772,8.9,46,tvSeries,The Count: Love and Honor,El Conde: Amor y honor,0,2024,60,drama revenge count zambrano years loves conv...
15,82708,The First Years,The First Years is a Dutch series for young pe...,Soap Drama,high-school mockumentary young-adult,2014-05-26,"['Yuna', 'Ryan', 'Amir', 'Jade', 'Ramses', 'Vi...",1656.425,tt4469214,4.5,140,tvSeries,Brugklas,Brugklas,0,2014,10,soap drama high-school mockumentary young-adul...
16,252373,A Promessa,A Promessa,Drama,,2024-06-18,"['Verónica Rocha Morais', 'Laura Rocha', 'Olga...",1339.342,tt31860590,7.8,18,tvSeries,A Promessa,A Promessa,0,2024,\N,drama promessa
17,246331,Su Ji and U Ri,A healing romance begins between fallen star d...,Family Drama,affectation angry familiar hopeful joyful,2024-03-25,"['Jin Su-ji', 'Choi U-ri', 'Chae Sun-young', '...",1314.974,tt31908553,8.6,16,tvSeries,Su Ji and U Ri,Soojimazeun Woori,0,2024,30,family drama affectation angry familiar hopefu...
18,206559,Binnelanders,A South African Afrikaans soap opera. It is se...,Soap,afrikaans hospital soap dramatic drama,2005-10-13,"['Dr. At Koster', 'Dr. Tertius Jonker', 'Dr. C...",1226.378,tt1527854,7.6,62,tvSeries,Binnelanders,Binnelanders,0,2005,\N,soap afrikaans hospital soap dramatic drama st...
19,18770,Gran Hermano,Gran Hermano is a reality television series br...,Reality,,2000-04-23,"['Presentador', 'Presentador Debates']",1197.195,tt0262163,2.2,181,tvSeries,Gran hermano,Gran hermano,0,2000,\N,reality gran television big series endemol he...

In [ ]:
df.

In [7]:
df = pd.read_csv('../datasets/final_tvShows_df_full.csv')

In [32]:
df.to_csv('../datasets/final_tvShows_df_full.csv')

In [33]:
used_data = df[['id', 'title', 'popularity', 'imdb_id', 'averageRating',
       'numVotes', 'titleType', 'startYear', 'tags']].rename({
        'numVotes': 'num_votes', 
        'titleType': 'title_type', 
        'startYear':'start_year'
       },axis = 1)

In [34]:
used_data.to_csv('../datasets/final_tvShows_df.csv')