# Install additional libraries

In [1]:
%pip install IMDbPY

Requirement already satisfied: IMDbPY in c:\users\lenovo\miniconda3\lib\site-packages (2022.7.9)
Requirement already satisfied: cinemagoer in c:\users\lenovo\miniconda3\lib\site-packages (from IMDbPY) (2023.5.1)
Requirement already satisfied: SQLAlchemy in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (2.0.31)
Requirement already satisfied: lxml in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (4.6.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

# Import Libraries

In [2]:
# Data gathering libraries
from imdb import IMDb
import requests as req
import gzip as gz
import json

In [3]:
# Data Analysis Libraries
import pandas as pd
import numpy as np

In [4]:
# Visualization libaries
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# NLP libraies
import nltk
from nltk.tokenize import word_tokenize
import spacy

In [6]:
# additional libraries
import pprint
from tqdm import tqdm
import pickle as pkl
import warnings
warnings.filterwarnings('ignore')
import sys
from collections import Counter

# Data Gathering

## Retriving Data from tmdb API

In [7]:
discover_urls = [f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page={i}" for i in range(1,501)]

urls = {
    'keywords' : "https://api.themoviedb.org/3/movie/movie_id/keywords",
    
    'details' : "https://api.themoviedb.org/3/movie/movie_id?append_to_response=title&language=en-US",
    
    'credit' : "https://api.themoviedb.org/3/movie/movie_id/credits?language=en-US",

    'collection': "https://api.themoviedb.org/3/collection/collection_id?language=en-US"
}

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MDM0ZGRiZTc2MjBlNDA5YmIyZTFjYWY4YTQzM2JjOSIsInN1YiI6IjY0ZmY0NjA1ZWIxNGZhMDBhZGE1ZDU4ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jDadAw2N_wZERgQvHIqf-7XGKyORY1MQiw8DlIC09H8"
}

In [216]:
movies_results = []
for discover_url in tqdm(discover_urls):
    res = req.get(discover_url, headers=headers)
    movies_results.extend(res.json()['results'])

100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [01:08<00:00,  7.29it/s]

In [9]:
movies = {
    "id" : [],
    "title": [],
    "overview": [],
    "release_date":[],
    "popularity":[],
    "imdb_id": [],
    "genres": [],
    "keywords":[],
    "characters":[],
}

In [232]:
fill_data(movies_results)

100%|███████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 1417281.88it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 9099/9099 [38:41<00:00,  3.92it/s]

ids filled

In [234]:
pd.DataFrame({'tmdb_id':movies['id']}).to_json('tmdb_ids.json')

In [10]:
movies['id'] = pd.read_json('tmdb_ids.json').tmdb_id.to_list()

In [32]:
movies_df = load_data(ids=movies['id'],media_type='movies',obs=movies)

movies data: 100%|███████████████████████████████████████████████████████████████| 10142/10142 [44:12<00:00,  3.82it/s]

ValueError: All arrays must be of the same length

In [428]:



for movie_id in tqdm(movies['id']):

100%|████████████████████████████████████████████████████████████████████████████| 10142/10142 [35:59<00:00,  4.70it/s]

In [38]:
movies['characters'] = []

for movie_id in tqdm(movies['id'],desc='Characters'):

100%|████████████████████████████████████████████████████████████████████████████| 10142/10142 [32:53<00:00,  5.14it/s]

In [41]:
for key,value in mov_studio.items():
  print(key,'=>',len(value),type(value[0]))

director_ids => 10142 [16767]
actor_ids => 10142 [4826, 5999, 4828, 53508, 1086499, 222320, 1086500, 2307211, 148389, 1761924, 2651471, 106172, 69552, 2651474, 1294421, 2651478, 2651481, 2651483, 2651486, 2651487, 2651488, 2651489, 2651491, 3457313, 4831, 2159274, 3479164, 2651545, 1303969, 16767, 1381113, 3477088, 1912097]
characters => 10142 ['Nikander', 'Ilona', 'Melartin', "Nikander's Co-Worker", "Ilona's Friend", 'Store Manager', 'Third Man', 'Police Officer', "Nikander's Sister", 'Pianist', '2nd Pianist', 'Pelle', 'Staffan', "Melartin's Wife", 'Cook', 'Singer', 'Man in Restaurant', 'Police Officer', 'Porter', 'Woman in Restaurant', 'Hostess', 'Garbage Man / Bartender', "Melartin's Daughter", 'Keyboardist (uncredited)', 'Guard (uncredited)', 'Woman in Restaurant (uncredited)', 'Bingo Player (uncredited)', 'Bingo Player (uncredited)', 'Woman in Restaurant (uncredited)', 'Hotel Receptionist (uncredited)', 'Customer (uncredited)', 'Woman in Cinema (uncredited)', 'Garbage Man (uncredited)']

In [437]:
movies_data = pd.DataFrame().from_dict(movies)

In [12]:
movies_data.to_json('../datasets/movies_with_collection_and_characters.json')

NameError: name 'movies_data' is not defined

In [9]:
movies['id'] = list(pd.read_json('tmdb_ids.json').tmdb_id.values)

NameError: name 'movies' is not defined

In [316]:
len(movies['id'])

10142

In [10]:
movies = pd.read_json('../datasets/movies_with_collection_and_characters.json').to_dict()

In [13]:
# df_movies = pd.read_csv('movies.csv',lineterminator='\n').iloc[:,1:]
df_movies = pd.read_json('../datasets/movies_with_collection_and_characters.json')

In [15]:
for col in df_movies.columns:
    print(col,'\n',df_movies[col].value_counts())

id
 3          1
1034060    1
18239      1
18240      1
345920     1
          ..
960481     1
698338     1
10213      1
10214      1
1146225    1
Name: id, Length: 10142, dtype: int64
title
 The Girl Next Door                  3
The House                           3
Venom                               3
All Quiet on the Western Front      3
Escape Room                         3
                                   ..
The Way We Were                     1
Cries and Whispers                  1
What Ever Happened to Baby Jane?    1
The Flight of the Phoenix           1
Escaping Paradise                   1
Name: title, Length: 9873, dtype: int64
overview
               199
2024-09-26     47
2024-09-27     43
2024-09-25     23
2024-09-24     23
             ...
2004-03-23      1
1997-07-02      1
2019-01-23      1
1988-11-09      1
1977-11-11      1
Name: overview, Length: 6353, dtype: int64
release_date
               38
-              2
tt0092149      1
tt16118262     1
tt5628418      1
              ..
tt12952242     1
tt0327437      1
tt0139462      1
tt15238852     1
tt11634048     1
Name: release_date, Length: 9697, dtype: int64
popularity
 -    10142
Name: popularity, dtype: int64
imdb_id
 -    10142
Name: imdb_id, dtype: int64
genres
                                                                                                                                                                                                                                                                                                                                                                                                                 116
Miser Ebenezer Scrooge is awakened on Christmas Eve by spirits who reveal to him his own miserable existence, what opportunities he wasted in his youth, his current cruelties, and the dire fate that awaits him if he does not change his ways. Scrooge is faced with his own story of growing bitterness and meanness, and must decide what his own future will hold: death or redemption.                     3
Explore the lure of the Old West and how it was won—and lost—through the blood, sweat and tears of many. Spanning 15 years before, during, and following the Civil War, from 1859 to 1874, embark on an emotional journey across a country at war with itself, experienced through the lens of families, friends and foes all attempting to discover what it truly means to be the United States of America.      3
After going to extremes to cover up an accident, a corrupt cop's life spirals out of control when he starts receiving threats from a mysterious witness.                                                                                                                                                                                                                                                          2
After trying to cover up a car accident that left a man dead, a crooked homicide detective is stalked by a mysterious man claiming to have witnessed the event.                                                                                                                                                                                                                                                   2
                                                                                                                                                                                                                                                                                                                                                                                                               ...
Dong-hoon is a detective who only has eyes for his foster daughter Yoon-ji. However, she's unemployed and only likes to party.  One day, she brings her friend Hye-ri home. Hye-ri doesn't leave and acts as though she lives there, even bringing her boyfriend into the house for some adult playtime, tempting Dong-hoon.                                                                                      1
Narrowly escaping death, outlaw Johnny Madrid goes on the run with the hangman's sensuous daughter Esmeralda by his side.                                                                                                                                                                                                                                                                                         1
Tim Avery, an aspiring cartoonist, finds himself in a predicament when his dog stumbles upon the mask of Loki. Then after conceiving an infant son "born of the mask", he discovers just how looney child raising can be.                                                                                                                                                                                         1
An unexpected affair quickly escalates into a heart-stopping reality for two women whose passionate connection changes their lives forever.                                                                                                                                                                                                                                                                       1
When a young couple vacations on an exotic island, they encounter a dangerous fugitive who is determined to keep them from leaving.                                                                                                                                                                                                                                                                               1
Name: genres, Length: 10014, dtype: int64
keywords
 []                                                                                                                                                                                                                                                                                                  1275
[softcore]                                                                                                                                                                                                                                                                                           195
[anime]                                                                                                                                                                                                                                                                                               65
[sequel]                                                                                                                                                                                                                                                                                              25
[softcore, pink film]                                                                                                                                                                                                                                                                                 18
                                                                                                                                                                                                                                                                                                    ...
[based on novel or book, shanghai, china, stadium, bravery, peasant, prisoner of war, coming of age, pacific war, chinese, japanese army, japanese soldier, japanese surrender, salt mine, internment camp, child protagonist, children in wartime, japanese occupation of china, suzhou, china]       1
[human animal relationship, dog, arsonist, pets]                                                                                                                                                                                                                                                       1
[sea, diamond, cruise, school trip, disappearance, spring break, jewel theft, sex comedy, national lampoon's, college student]                                                                                                                                                                         1
[suicide, call girl, childhood friends, grotesque]                                                                                                                                                                                                                                                     1
[based on novel or book, escape, resistance, dystopia, maze, post-apocalyptic future, infection, on the run, zombie, storm, disease, desert, sewer, antidote, corporation, virus, runner, city ruin, immunity, based on young adult novel]                                                             1
Name: keywords, Length: 8300, dtype: int64
director_ids
 []    10142
Name: director_ids, dtype: int64
characters
 []    10142
Name: characters, dtype: int64
actor_ids
 []    10142
Name: actor_ids, dtype: int64
movie_imdb_id
 0.000     20
15.504     6
16.115     6
15.462     5
16.283     5
          ..
25.509     1
10.815     1
26.338     1
51.529     1
23.230     1
Name: movie_imdb_id, Length: 8887, dtype: int64
movie_popularity
 [Drama]                                    545
[Comedy]                                   369
[Drama, Romance]                           292
[Horror, Thriller]                         241
[Horror]                                   238
                                          ...
[Drama, Adventure, Action, History]          1
[Drama, Animation, Family]                   1
[Music, Drama, History]                      1
[Adventure, Animation, Family, Romance]      1
[TV Movie, Comedy, Family, Horror]           1
Name: movie_popularity, Length: 2294, dtype: int64

In [18]:
df_movies.head()

,id,title,overview,release_date,popularity,imdb_id,genres,keywords,director_ids,characters,actor_ids,movie_imdb_id,movie_popularity
0,3,Shadows in Paradise,1986-10-17,tt0092149,-,-,"Nikander, a rubbish collector and would-be ent...","[helsinki, finland, salesclerk, garbage]",[],[],[],10.868,"[Comedy, Drama, Romance]"
1,983044,The Arctic Convoy,2023-12-25,tt27724113,-,-,"In 1942, a convoy of 35 civilian ships, carryi...","[world war ii, based on true story, norwegian ...",[],[],[],17.56,"[War, Drama]"
2,22,Pirates of the Caribbean: The Curse of the Bla...,2003-07-09,tt0325980,-,-,After Port Royal is attacked and pillaged by a...,"[blacksmith, east india company, gold, exotic ...",[],[],[],115.585,"[Adventure, Fantasy, Action]"
3,327833,Skin Trade,2014-11-07,tt1641841,-,-,After his family is killed by a Serbian gangst...,"[martial arts, human trafficking, bangkok, tha...",[],[],[],14.415,"[Thriller, Action, Drama]"
4,67343,Mr. Vampire II,1986-08-15,tt0091293,-,-,Chaos ensues after a team of archaeologists ac...,[],[],[],[],10.921,"[Horror, Action, Comedy]"

In [14]:
df_movies[df_movies['movie_imdb_id'].isnull()]

Empty DataFrame
Columns: [id, title, overview, release_date, popularity, imdb_id, genres, keywords, director_ids, characters, actor_ids, movie_imdb_id, movie_popularity]
Index: []

In [15]:
df_movies[df_movies['movie_imdb_id'] == '']

Empty DataFrame
Columns: [id, title, overview, release_date, popularity, imdb_id, genres, keywords, director_ids, characters, actor_ids, movie_imdb_id, movie_popularity]
Index: []

In [17]:
df_movies['movie_imdb_id'].value_counts()

0.000     20
15.504     6
16.115     6
15.462     5
16.283     5
          ..
25.509     1
10.815     1
26.338     1
51.529     1
23.230     1
Name: movie_imdb_id, Length: 8887, dtype: int64

In [ ]:
df_movies.info()

In [12]:
df_movies.drop(df_movies[(df_movies['movie_imdb_id'] == '') | (df_movies['movie_imdb_id'].isnull())].index,inplace=True)

In [13]:
df_movies.reset_index(inplace=True)
df_movies.drop(columns=['index'],inplace=True)

In [14]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   9752 non-null   int64
 1   title                9752 non-null   object
 2   overview             9752 non-null   object
 3   genres               9752 non-null   object
 4   keywords             9752 non-null   object
 5   release_date         9752 non-null   object
 6   director             9752 non-null   object
 7   director_popularity  9752 non-null   object
 8   movie_popularity     9752 non-null   float64
 9   movie_imdb_id        9752 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 762.0+ KB

## Filling missing Values

In [15]:
def get_director_name_and_popularity(id):
    if 'director' in (IMDb().get_movie(id).data.keys()):
        director_name = (IMDb()
                        .get_movie(id)
                        .data['director'][0]
                        .data['name']
        )
        url = ('https://api.themoviedb.org/3/search/person?query={}&include_adult=false&language=en-US&page=1'
                .format(director_name.strip().replace(" ","%20"))
              )

        results = (req
                      .get(url,headers=headers)
                      .json()['results']
        )

        if len(results) > 0:
            popularity = results[0]['popularity']
        else:
            popularity = 0.0
            
    else:
          director_name = '-'
          popularity = 0.0
          
    return {'director_name':director_name,
                'director_popularity':popularity}

In [18]:
director_names = []
director_popularity = []
for index in tqdm(df_movies.index):
  if df_movies.iloc[index]['director'] == []:
    director_information = get_director_name_and_popularity(df_movies.iloc[index]['movie_imdb_id'][2:])
    director_names.append(director_information['director_name'])
    director_popularity.append(director_information['director_popularity'])
  else:
    director_names.append(df_movies.iloc[index]['director'])
    director_popularity.append(df_movies.iloc[index]['director_popularity'])

df_movies['director'] = director_names
df_movies['director_popularity'] = director_popularity

100%|█████████████████████████████████████████████████████████████████████████████| 9752/9752 [01:29<00:00, 108.38it/s]

## Integrate data from IMDb Bulk Dataset

In [22]:
ratings = pd.read_csv(gz.open("datasets/title.ratings.tsv.gz"),sep="\t")
ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2084
1  tt0000002            5.6       281
2  tt0000003            6.5      2086
3  tt0000004            5.4       182
4  tt0000005            6.2      2820

In [23]:
basics = pd.read_csv(gz.open("datasets/title.basics.tsv.gz"),delimiter='\t')

In [24]:
imdb_genres = basics.genres

In [25]:
basics.drop(columns=['genres'],inplace = True)

In [26]:
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,5
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1

In [ ]:
principals = pd.read_csv(gz.open("datasets/title.principals.tsv.gz"),sep='\t',encoding='utf-8',lineterminator='\n')

In [ ]:
principals.head()

In [27]:
df_1 = pd.merge(df_movies,ratings,how='inner',right_on='tconst',left_on = 'movie_imdb_id').drop(columns='tconst')

In [28]:
df_1.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709

In [29]:
df_2 = pd.merge(df_1,basics,how='inner',right_on='tconst',left_on='movie_imdb_id').drop(columns = ["tconst"])

In [30]:
df_2.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [31]:
sys.getsizeof(df_2)

13783197

In [32]:
df_2.to_csv('movies_df.csv')

# Dealing with DataBase

## Data Base API

In [385]:
movies_df = pd.read_csv('../datasets/movies_df.csv')

In [386]:
movies_df.head()

,Unnamed: 0,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,0,365177,Borderlands,"Returning to her home planet, an infamous boun...","['Action', 'Science Fiction', 'Comedy', 'Adven...","['outlaw', 'based on video game', 'unlikely fr...",2024-08-07,['Eli Roth'],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"['Action', 'Comedy', 'Science Fiction']","['hero', 'superhero', 'anti hero', 'mutant', '...",2024-07-24,['Shawn Levy'],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","['Comedy', 'Horror', 'Fantasy']","['afterlife', 'haunted house', 'sequel', 'para...",2024-09-04,['Tim Burton'],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"['Animation', 'Family', 'Adventure', 'Comedy']","['sadness', 'disgust', 'sequel', 'computer ani...",2024-06-11,['Kelsey Mann'],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","['Action', 'Thriller', 'Crime']",[],2024-08-22,['John Woo'],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [387]:
movies_df['genres'].iloc[1]

"['Action', 'Comedy', 'Science Fiction']"

In [388]:
for col in ['genres','keywords','director','director_popularity']:
    movies_df[col] = movies_df[col].apply(lambda x: x.replace("[","").replace("]","").replace("'","").split(","))

In [389]:
movies_df.head()

,Unnamed: 0,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure...","[outlaw, based on video game, unlikely frien...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, break...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranorm...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animati...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [390]:
movies_df['endYear'] = movies_df['endYear'].replace({'\\N':'-'})

In [391]:
movies_df.drop('Unnamed: 0',axis = 1, inplace = True)

In [392]:
movies_df.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure...","[outlaw, based on video game, unlikely frien...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,-,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, break...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,-,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranorm...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,-,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animati...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,-,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,-,126

In [393]:
req.delete('http://localhost:8080/delete')

## Inserting Data

In [394]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9585 entries, 0 to 9584
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   9585 non-null   int64
 1   title                9585 non-null   object
 2   overview             9573 non-null   object
 3   genres               9585 non-null   object
 4   keywords             9585 non-null   object
 5   release_date         9584 non-null   object
 6   director             9585 non-null   object
 7   director_popularity  9585 non-null   object
 8   movie_popularity     9585 non-null   float64
 9   movie_imdb_id        9585 non-null   object
 10  averageRating        9585 non-null   float64
 11  numVotes             9585 non-null   int64
 12  titleType            9585 non-null   object
 13  primaryTitle         9585 non-null   object
 14  originalTitle        9585 non-null   object
 15  isAdult              9585 non-null   int64
 16  startYear            9585 non-null   int64
 17  endYear              9585 non-null   object
 18  runtimeMinutes       9585 non-null   object
dtypes: float64(2), int64(4), object(13)
memory usage: 1.4+ MB

In [395]:
movies_df['runtimeMinutes'].replace({'\\N':0},inplace=True)

In [396]:
movies_df['runtimeMinutes'] = movies_df['runtimeMinutes'].astype(int)

In [397]:
movies_df.rename(columns=
    {
        "averageRating": "movie_imdb_rating",
        "numVotes":"num_votes",
        "titleType": "title_type",
        "primaryTitle": "primary_title",
        "originalTitle": "original_title",
        "isAdult":"is_adult",
        "startYear":"start_year",
        "endYear":"end_year",
        "runtimeMinutes": "runtime_minutes"
    }
,inplace=True)

In [398]:
movies_documents = movies_df.drop(columns = ['title_type','primary_title','original_title','is_adult','end_year']).T.to_dict()

In [399]:
first_it = movies_documents[0]

In [400]:
first_it

{'id': 365177,
 'title': 'Borderlands',
 'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
 'genres': ['Action',
  ' Science Fiction',
  ' Comedy',
  ' Adventure',
  ' Thriller'],
 'keywords': ['outlaw',
  ' based on video game',
  ' unlikely friendship',
  ' talking robot',
  ' missing girl',
  ' band of misfits',
  ' mysterious power'],
 'release_date': '2024-08-07',
 'director': ['Eli Roth'],
 'director_popularity': ['24.36'],
 'movie_popularity': 2388.352,
 'movie_imdb_id': 'tt4978420',
 'movie_imdb_rating': 4.5,
 'num_votes': 23064,
 'runtime_minutes': 101}

In [401]:
for key in first_it.keys():
    print(key,'->',type(first_it[key]))

id -> <class 'int'>
title -> <class 'str'>
overview -> <class 'str'>
genres -> <class 'list'>
keywords -> <class 'list'>
release_date -> <class 'str'>
director -> <class 'list'>
director_popularity -> <class 'list'>
movie_popularity -> <class 'float'>
movie_imdb_id -> <class 'str'>
movie_imdb_rating -> <class 'float'>
num_votes -> <class 'int'>
runtime_minutes -> <class 'int'>

In [402]:
# id: int
# title: str
# overview:str 
# genres: list
# keywords: list
# release_date: str
# director: list
# director_popularity:list
# movie_popularity:float
# movie_imdb_id:str 
# movie_imdb_rating:float
# runtime_minutes:int

In [403]:
movie_docs = list(movies_documents.values())

In [404]:
movie_docs[:4]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'num_votes': 23064,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'num_votes': 275259,
  'runtime_minutes': 128},
 {'id': 917496,
  'title': 'Beetlejuice Beetlejuice',
  'overview': "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
  'genres': ['Comedy', ' Horror', ' Fantasy'],
  'keywords': ['afterlife',
   ' haunted house',
   ' sequel',
   ' paranormal',
   ' teenage girl',
   ' gothic',
   ' death',
   ' new england',
   ' ghost',
   ' horror comedy',
   ' unexpected death',
   ' mother daughter relationship',
   ' fantasy',
   ' fantasy comedy'],
  'release_date': '2024-09-04',
  'director': ['Tim Burton'],
  'director_popularity': ['33.964'],
  'movie_popularity': 1567.733,
  'movie_imdb_id': 'tt2049403',
  'movie_imdb_rating': 7.1,
  'num_votes': 25446,
  'runtime_minutes': 105},
 {'id': 1022789,
  'title': 'Inside Out 2',
  'overview': "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  'genres': ['Animation', ' Family', ' Adventure', ' Comedy'],
  'keywords': ['sadness',
   ' disgust',
   ' sequel',
   ' computer animation',
   ' teenage girl',
   ' fear',
   ' anger',
   ' envy',
   ' aftercreditsstinger',
   ' duringcreditsstinger',
   ' emotions',
   ' embarrasment',
   ' anxious',
   ' joy',
   ' anxiety',
   ' frustrated'],
  'release_date': '2024-06-11',
  'director': ['Kelsey Mann'],
  'director_popularity': ['13.717'],
  'movie_popularity': 1485.085,
  'movie_imdb_id': 'tt22022452',
  'movie_imdb_rating': 7.7,
  'num_votes': 126369,
  'runtime_minutes': 96}]

In [405]:
res.json()

{'acknowledged': True,

In [373]:
movies_docs = json.dumps(movie_docs)

In [374]:
movies_data = json.loads(movies_docs)

In [375]:
type(movies_data)

list

In [376]:
movies_data[:2]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'num_votes': 23064,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'num_votes': 275259,
  'runtime_minutes': 128}]

In [299]:
mov_df = pd.DataFrame().from_dict(movies_data)

In [300]:
mov_df['overview'].fillna('-',inplace=True)

In [301]:
mov_df.drop('release_date',axis = 1, inplace=True)

In [407]:
mov_df.isnull().sum()

id                     0
title                  0
overview               0
genres                 0
keywords               0
release_date           0
director               0
director_popularity    0
movie_popularity       0
movie_imdb_id          0
movie_imdb_rating      0
num_votes              0
runtime_minutes        0
dtype: int64

In [408]:
movies_data = list(mov_df.T.to_dict().values())

In [409]:
movies_data[:5]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'num_votes': 23064,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'num_votes': 275259,
  'runtime_minutes': 128},
 {'id': 917496,
  'title': 'Beetlejuice Beetlejuice',
  'overview': "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
  'genres': ['Comedy', ' Horror', ' Fantasy'],
  'keywords': ['afterlife',
   ' haunted house',
   ' sequel',
   ' paranormal',
   ' teenage girl',
   ' gothic',
   ' death',
   ' new england',
   ' ghost',
   ' horror comedy',
   ' unexpected death',
   ' mother daughter relationship',
   ' fantasy',
   ' fantasy comedy'],
  'release_date': '2024-09-04',
  'director': ['Tim Burton'],
  'director_popularity': ['33.964'],
  'movie_popularity': 1567.733,
  'movie_imdb_id': 'tt2049403',
  'movie_imdb_rating': 7.1,
  'num_votes': 25446,
  'runtime_minutes': 105},
 {'id': 1022789,
  'title': 'Inside Out 2',
  'overview': "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  'genres': ['Animation', ' Family', ' Adventure', ' Comedy'],
  'keywords': ['sadness',
   ' disgust',
   ' sequel',
   ' computer animation',
   ' teenage girl',
   ' fear',
   ' anger',
   ' envy',
   ' aftercreditsstinger',
   ' duringcreditsstinger',
   ' emotions',
   ' embarrasment',
   ' anxious',
   ' joy',
   ' anxiety',
   ' frustrated'],
  'release_date': '2024-06-11',
  'director': ['Kelsey Mann'],
  'director_popularity': ['13.717'],
  'movie_popularity': 1485.085,
  'movie_imdb_id': 'tt22022452',
  'movie_imdb_rating': 7.7,
  'num_votes': 126369,
  'runtime_minutes': 96},
 {'id': 970347,
  'title': 'The Killer',
  'overview': 'Zee is a feared contract killer known as "the Queen of the Dead," but when she refuses to murder a young blind woman, she finds herself hunted both by criminal colleagues and a determined police detective.',
  'genres': ['Action', ' Thriller', ' Crime'],
  'keywords': [''],
  'release_date': '2024-08-22',
  'director': ['John Woo'],
  'director_popularity': ['16.765'],
  'movie_popularity': 1084.443,
  'movie_imdb_id': 'tt1121948',
  'movie_imdb_rating': 5.7,
  'num_votes': 6709,
  'runtime_minutes': 126}]

In [410]:
res = req.post(url='http://localhost:8080/post/data',json={'movies':movies_data})

In [411]:
res.json()

{'acknowledged': True,

## Retrieving Data

In [421]:
res = req.get(url='http://localhost:8080/get/all')

In [422]:
res.status_code

200

In [423]:
res.json()[0].keys()

dict_keys(['id', 'title', 'overview', 'genres', 'keywords', 'release_date', 'director', 'director_popularity', 'movie_popularity', 'movie_imdb_id', 'movie_imdb_rating', 'num_votes', 'runtime_minutes'])

In [424]:
df = pd.DataFrame().from_dict(res.json())

# Data Preprocessing

In [425]:
df.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,num_votes,runtime_minutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure...","[outlaw, based on video game, unlikely frien...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, break...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranorm...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animati...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,126

In [426]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9585 entries, 0 to 9584
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   9585 non-null   int64
 1   title                9585 non-null   object
 2   overview             9585 non-null   object
 3   genres               9585 non-null   object
 4   keywords             9585 non-null   object
 5   release_date         9585 non-null   object
 6   director             9585 non-null   object
 7   director_popularity  9585 non-null   object
 8   movie_popularity     9585 non-null   float64
 9   movie_imdb_id        9585 non-null   object
 10  movie_imdb_rating    9585 non-null   float64
 11  num_votes            9585 non-null   int64
 12  runtime_minutes      9585 non-null   int64
dtypes: float64(2), int64(3), object(8)
memory usage: 973.6+ KB

In [427]:
df['release_date'].replace({'-':np.nan},inplace=True)

In [428]:
df['startYear'] = pd.to_datetime(df['release_date']).dt.year

In [429]:
with open('../datasets/stopwords.txt','r') as stopfp:
    stop_words = stopfp.readlines()

In [430]:
stop_words = stop_words[0].replace('"','').split(', ')

In [431]:
stop_words

['0o',
 '0s',
 '3a',
 '3b',
 '3d',
 '6b',
 '6o',
 'a',
 'a1',
 'a2',
 'a3',
 'a4',
 'ab',
 'able',
 'about',
 'above',
 'abst',
 'ac',
 'accordance',
 'according',
 'accordingly',
 'across',
 'act',
 'actually',
 'ad',
 'added',
 'adj',
 'ae',
 'af',
 'affected',
 'affecting',
 'affects',
 'after',
 'afterwards',
 'ag',
 'again',
 'against',
 'ah',
 'ain',
 "ain't",
 'aj',
 'al',
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'announce',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'ao',
 'ap',
 'apart',
 'apparently',
 'appear',
 'appreciate',
 'appropriate',
 'approximately',
 'ar',
 'are',
 'aren',
 'arent',
 "aren't",
 'arise',
 'around',
 'as',
 "a's",
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'au',
 'auth',
 'av',
 'available',
 'aw',
 'away',
 'awfully',
 'ax',
 'ay',
 'az',
 'b',
 'b1',
 'b2',
 'b3',
 'ba',
 'back',
 'bc',
 'bd',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'begin',
 'beginning',
 'beginnings',
 'begins',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'bi',
 'bill',
 'biol',
 'bj',
 'bk',
 'bl',
 'bn',
 'both',
 'bottom',
 'bp',
 'br',
 'brief',
 'briefly',
 'bs',
 'bt',
 'bu',
 'but',
 'bx',
 'by',
 'c',
 'c1',
 'c2',
 'c3',
 'ca',
 'call',
 'came',
 'can',
 'cannot',
 'cant',
 "can't",
 'cause',
 'causes',
 'cc',
 'cd',
 'ce',
 'certain',
 'certainly',
 'cf',
 'cg',
 'ch',
 'changes',
 'ci',
 'cit',
 'cj',
 'cl',
 'clearly',
 'cm',
 "c'mon",
 'cn',
 'co',
 'com',
 'come',
 'comes',
 'con',
 'concerning',
 'consequently',
 'consider',
 'considering',
 'contain',
 'containing',
 'contains',
 'corresponding',
 'could',
 'couldn',
 'couldnt',
 "couldn't",
 'course',
 'cp',
 'cq',
 'cr',
 'cry',
 'cs',
 "c's",
 'ct',
 'cu',
 'currently',
 'cv',
 'cx',
 'cy',
 'cz',
 'd',
 'd2',
 'da',
 'date',
 'dc',
 'dd',
 'de',
 'definitely',
 'describe',
 'described',
 'despite',
 'detail',
 'df',
 'di',
 'did',
 'didn',
 "didn't",
 'different',
 'dj',
 'dk',
 'dl',
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 'done',
 "don't",
 'down',
 'downwards',
 'dp',
 'dr',
 'ds',
 'dt',
 'du',
 'due',
 'during',
 'dx',
 'dy',
 'e',
 'e2',
 'e3',
 'ea',
 'each',
 'ec',
 'ed',
 'edu',
 'ee',
 'ef',
 'effect',
 'eg',
 'ei',
 'eight',
 'eighty',
 'either',
 'ej',
 'el',
 'eleven',
 'else',
 'elsewhere',
 'em',
 'empty',
 'en',
 'end',
 'ending',
 'enough',
 'entirely',
 'eo',
 'ep',
 'eq',
 'er',
 'es',
 'especially',
 'est',
 'et',
 'et-al',
 'etc',
 'eu',
 'ev',
 'even',
 'ever',
 'every',
 'everybody',
 'everyone',
 'everything',
 'everywhere',
 'ex',
 'exactly',
 'example',
 'except',
 'ey',
 'f',
 'f2',
 'fa',
 'far',
 'fc',
 'few',
 'ff',
 'fi',
 'fifteen',
 'fifth',
 'fify',
 'fill',
 'find',
 'fire',
 'first',
 'five',
 'fix',
 'fj',
 'fl',
 'fn',
 'fo',
 'followed',
 'following',
 'follows',
 'for',
 'former',
 'formerly',
 'forth',
 'forty',
 'found',
 'four',
 'fr',
 'from',
 'front',
 'fs',
 'ft',
 'fu',
 'full',
 'further',
 'furthermore',
 'fy',
 'g',
 'ga',
 'gave',
 'ge',
 'get',
 'gets',
 'getting',
 'gi',
 'give',
 'given',
 'gives',
 'giving',
 'gj',
 'gl',
 'go',
 'goes',
 'going',
 'gone',
 'got',
 'gotten',
 'gr',
 'greetings',
 'gs',
 'gy',
 'h',
 'h2',
 'h3',
 'had',
 'hadn',
 "hadn't",
 'happens',
 'hardly',
 'has',
 'hasn',
 'hasnt',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'hed',
 "he'd",
 "he'll",
 'hello',
 'help',
 'hence',
 'her',
 'here',
 'hereafter',
 'hereby',
 'herein',
 'heres',
 "here's",
 'hereupon',
 'hers',
 'herself',
 'hes',
 "he's",
 'hh',
 'hi',
 'hid',
 'him',
 'himself',
 'his',
 'hither',
 'hj',
 'ho',
 'home',
 'hopefully',
 'how',
 'howbeit',
 'however',
 "how's",
 'hr',
 'hs',
 'http',
 'hu',
 'hundred',
 'hy',
 'i',
 'i2',
 'i3',
 'i4',
 'i6',
 'i7',
 'i8',
 'ia',
 'ib',
 'ibid',
 'ic',
 'id',
 "i'd",
 'ie',
 'if',
 'ig',
 'ignored',
 'ih',
 'ii',
 'ij',
 'il',
 "i'll",
 'im',
 "i'm",
 'immediate',
 'immediately',
 'importance',
 'important',
 'in',
 'inasmuch',
 'inc',
 'indeed',
 'index',
 'indicate',
 'indicated',
 'indicates',
 'information',
 'inner',
 'insofar',
 'instead',
 'interest',
 'into',
 'invention',
 'inward',
 'io',
 'ip',
 'iq',
 'ir',
 'is',
 'isn',
 "isn't",
 'it',
 'itd',
 "it'd",
 "it'll",
 'its',
 "it's",
 'itself',
 'iv',
 "i've",
 'ix',
 'iy',
 'iz',
 'j',
 'jj',
 'jr',
 'js',
 'jt',
 'ju',
 'just',
 'k',
 'ke',
 'keep',
 'keeps',
 'kept',
 'kg',
 'kj',
 'km',
 'know',
 'known',
 'knows',
 'ko',
 'l',
 'l2',
 'la',
 'largely',
 'last',
 'lately',
 'later',
 'latter',
 'latterly',
 'lb',
 'lc',
 'le',
 'least',
 'les',
 'less',
 'lest',
 'let',
 'lets',
 "let's",
 'lf',
 'like',
 'liked',
 'likely',
 'line',
 'little',
 'lj',
 'll',
 'll',
 'ln',
 'lo',
 'look',
 'looking',
 'looks',
 'los',
 'lr',
 'ls',
 'lt',
 'ltd',
 'm',
 'm2',
 'ma',
 'made',
 'mainly',
 'make',
 'makes',
 'many',
 'may',
 'maybe',
 'me',
 'mean',
 'means',
 'meantime',
 'meanwhile',
 'merely',
 'mg',
 'might',
 'mightn',
 "mightn't",
 'mill',
 'million',
 'mine',
 'miss',
 'ml',
 'mn',
 'mo',
 'more',
 'moreover',
 'most',
 'mostly',
 'move',
 'mr',
 'mrs',
 'ms',
 'mt',
 'mu',
 'much',
 'mug',
 'must',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'n',
 'n2',
 'na',
 'name',
 'namely',
 'nay',
 'nc',
 'nd',
 'ne',
 'near',
 'nearly',
 'necessarily',
 'necessary',
 'need',
 'needn',
 "needn't",
 'needs',
 'neither',
 'never',
 'nevertheless',
 'new',
 'next',
 'ng',
 'ni',
 'nine',
 'ninety',
 'nj',
 'nl',
 'nn',
 'no',
 'nobody',
 'non',
 'none',
 'nonetheless',
 'noone',
 'nor',
 'normally',
 'nos',
 'not',
 'noted',
 'nothing',
 'novel',
 'now',
 'nowhere',
 'nr',
 'ns',
 'nt',
 'ny',
 'o',
 'oa',
 'ob',
 'obtain',
 'obtained',
 'obviously',
 'oc',
 'od',
 'of',
 'off',
 'often',
 'og',
 'oh',
 'oi',
 'oj',
 'ok',
 'okay',
 'ol',
 'old',
 'om',
 'omitted',
 'on',
 'once',
 'one',
 'ones',
 'only',
 'onto',
 'oo',
 'op',
 'oq',
 'or',
 'ord',
 'os',
 'ot',
 'other',
 'others',
 'otherwise',
 'ou',
 'ought',
 'our',
 'ours',
 'ourselves',
 'out',
 'outside',
 'over',
 'overall',
 'ow',
 'owing',
 'own',
 'ox',
 'oz',
 'p',
 'p1',
 'p2',
 'p3',
 'page',
 'pagecount',
 'pages',
 'par',
 'part',
 'particular',
 'particularly',
 'pas',
 'past',
 'pc',
 'pd',
 'pe',
 'per',
 'perhaps',
 'pf',
 'ph',
 'pi',
 'pj',
 'pk',
 'pl',
 'placed',
 'please',
 'plus',
 'pm',
 'pn',
 'po',
 'poorly',
 'possible',
 'possibly',
 'potentially',
 'pp',
 'pq',
 'pr',
 'predominantly',
 'present',
 'presumably',
 'previously',
 'primarily',
 'probably',
 'promptly',
 'proud',
 'provides',
 'ps',
 'pt',
 'pu',
 'put',
 'py',
 'q',
 'qj',
 'qu',
 'que',
 'quickly',
 'quite',
 'qv',
 'r',
 'r2',
 'ra',
 'ran',
 'rather',
 'rc',
 'rd',
 're',
 'readily',
 'really',
 'reasonably',
 'recent',
 'recently',
 'ref',
 'refs',
 'regarding',
 'regardless',
 'regards',
 'related',
 'relatively',
 'research',
 'research-articl',
 'respectively',
 'resulted',
 'resulting',
 'results',
 'rf',
 'rh',
 'ri',
 'right',
 'rj',
 'rl',
 'rm',
 'rn',
 'ro',
 'rq',
 'rr',
 'rs',
 'rt',
 'ru',
 'run',
 'rv',
 'ry',
 's',
 's2',
 'sa',
 'said',
 'same',
 'saw',
 'say',
 'saying',
 'says',
 'sc',
 'sd',
 'se',
 'sec',
 'second',
 'secondly',
 'section',
 'see',
 'seeing',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'seen',
 'self',
 'selves',
 'sensible',
 'sent',
 'serious',
 'seriously',
 'seven',
 'several',
 'sf',
 'shall',
 'shan',
 "shan't",
 'she',
 'shed',
 "she'd",
 "she'll",
 'shes',
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'show',
 'showed',
 'shown',
 'showns',
 'shows',
 'si',
 'side',
 'significant',
 'significantly',
 'similar',
 'similarly',
 'since',
 'sincere',
 'six',
 'sixty',
 'sj',
 'sl',
 'slightly',
 'sm',
 'sn',
 'so',
 'some',
 'somebody',
 'somehow',
 'someone',
 'somethan',
 'something',
 'sometime',
 'sometimes',
 'somewhat',
 'somewhere',
 'soon',
 'sorry',
 'sp',
 'specifically',
 'specified',
 'specify',
 'specifying',
 'sq',
 'sr',
 'ss',
 'st',
 'still',
 'stop',
 'strongly',
 'sub',
 'substantially',
 'successfully',
 'such',
 'sufficiently',
 'suggest',
 'sup',
 'sure',
 'sy',
 'system',
 'sz',
 't',
 't1',
 't2',
 't3',
 'take',
 'taken',
 'taking',
 'tb',
 'tc',
 'td',
 'te',
 'tell',
 'ten',
 'tends',
 'tf',
 'th',
 'than',
 'thank',
 'thanks',
 'thanx',
 'that',
 "that'll",
 'thats',
 "that's",
 "that've",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 'thereafter',
 'thereby',
 'thered',
 'therefore',
 'therein',
 "there'll",
 'thereof',
 'therere',
 'theres',
 "there's",
 'thereto',
 'thereupon',
 "there've",
 'these',
 'they',
 'theyd',
 "they'd",
 "they'll",
 'theyre',
 "they're",
 "they've",
 'thickv',
 'thin',
 'think',
 'third',
 'this',
 'thorough',
 'thoroughly',
 'those',
 'thou',
 'though',
 'thoughh',
 'thousand',
 'three',
 'throug',
 'through',
 'throughout',
 'thru',
 'thus',
 'ti',
 'til',
 'tip',
 'tj',
 'tl',
 'tm',
 'tn',
 'to',
 'together',
 'too',
 'took',
 'top',
 'toward',
 'towards',
 'tp',
 'tq',
 'tr',
 'tried',
 'tries',
 'truly',
 'try',
 'trying',
 'ts',
 "t's",
 'tt',
 'tv',
 'twelve',
 'twenty',
 'twice',
 'two',
 'tx',
 'u',
 'u201d',
 'ue',
 'ui',
 'uj',
 'uk',
 ...]

> #### after downloading it from `> spacy download en_core_web_lg` command

In [439]:
df = df[~df['movie_imdb_id'].duplicated()].reset_index().drop(columns = 'index')

In [440]:
# genres tags
genre_tags = df['genres'].apply(lambda x: ' '.join([i.strip().replace(' ','-') for i in x]).strip().lower()).to_list()

In [441]:
genre_tags[:5]

['action science-fiction comedy adventure thriller',
 'action comedy science-fiction',
 'comedy horror fantasy',
 'animation family adventure comedy',
 'action thriller crime']

In [442]:
# keywords tags 
keyword_tags = df['keywords'].apply(lambda x: ' '.join([i.strip().replace(' ','-') for i in x]).strip().lower()).to_list()

In [443]:
keyword_tags[:5]

['outlaw based-on-video-game unlikely-friendship talking-robot missing-girl band-of-misfits mysterious-power',
 'hero superhero anti-hero mutant breaking-the-fourth-wall marvel-cinematic-universe-(mcu) mutants superhero-teamup',
 'afterlife haunted-house sequel paranormal teenage-girl gothic death new-england ghost horror-comedy unexpected-death mother-daughter-relationship fantasy fantasy-comedy',
 'sadness disgust sequel computer-animation teenage-girl fear anger envy aftercreditsstinger duringcreditsstinger emotions embarrasment anxious joy anxiety frustrated',
 '']

In [444]:
overviews = df['overview']

In [445]:
# overview tags
overview_tags = []
for overview in tqdm(overviews):
    tags = []
    new_overview = ' '.join(set(tokenizer.tokenize(overview.lower())))
    word_token = word_tokenize(new_overview)
    for w in word_token:
        if (w.lower() not in stop_words):
            tags.append(w.replace(' ','-'))
    overview_tags.append(' '.join(tags).lower())

100%|████████████████████████████████████████████████████████████████████████████| 9509/9509 [00:06<00:00, 1398.50it/s]

In [446]:
overview_tags[:6]

['key dangerous protect heroes alliance power team girl bounty forms battle unexpected holds young unimaginable infamous planet bandits returning hunter monsters',
 'flexible listless existential wilson reluctantly wolverine mercenary threat morally wade homeworld days life toils civilian suit reluctant faces deadpool',
 'lydia daughter afterlife generations family accidentally haunted life tragedy opens turned deetz teenage return winter upside river beetlejuice astrid portal',
 'disgust feel fear room emotions sadness operation accounts long anxiety unexpected sudden mind joy demolition successful anger undergoing teenager running riley headquarters',
 'refuses feared zee finds murder woman criminal hunted colleagues police queen dead determined young contract detective blind killer',
 'big lok twelfth cyclone protect troubled fierce discovers series kowloon lessons accidentally close walled set friends resist battles order life city shin chan learns leadership vow youth chaos master amidst kwun enters villain safe invasion']

In [447]:
df.columns

Index(['id', 'title', 'overview', 'genres', 'keywords', 'release_date',
       'director', 'director_popularity', 'movie_popularity', 'movie_imdb_id',
       'movie_imdb_rating', 'num_votes', 'runtime_minutes', 'startYear'],
      dtype='object')

In [448]:
df['genres'] = genre_tags
df['keywords'] = keyword_tags
df['overview'] = overview_tags

In [63]:
genre_doc = []
keyword_doc = []
overview_doc = []
for i in tqdm(df.index):
    genre_doc.append(nlp(f'{genre_tags[i]}'))
    keyword_doc.append(nlp(f'{keyword_tags[i]}'))
    overview_doc.append(nlp(f'{overview_tags[i]}'))

100%|██████████████████████████████████████████████████████████████████████████████| 9509/9509 [03:05<00:00, 51.40it/s]

In [64]:
df['genre_doc'] = genre_doc
df['keyword_doc'] = keyword_doc
df['overview_doc'] = overview_doc

In [469]:
tags = []
for i in tqdm(df.index):
    tag = f'{genre_tags[i]} {keyword_tags[i]} {overview_tags[i]}'
    tags.append(tag)

100%|█████████████████████████████████████████████████████████████████████████| 9509/9509 [00:00<00:00, 1054815.71it/s]

In [125]:
import time

In [451]:
nlp_tags = []
start = time.time()
for i in tqdm(range(len(tags))):
    nlp_tag = nlp(u''.format(tag))
    nlp_tags.append(nlp_tag)
print(time.time() - start)

100%|████████████████████████████████████████████████████████████████████████████| 9509/9509 [00:01<00:00, 8167.78it/s]

1.1672394275665283

In [129]:
import sys
sys.getsizeof(tags)

85176

In [470]:
df['tags'] = tags

In [130]:
sys.getsizeof(df['tags'])

3364715

In [453]:
req.delete(url='http://localhost:8080/delete')

In [458]:
data = list(df.T.to_dict().values())

In [459]:
res = req.post(url='http://localhost:8080/post/data',json={'movies':data})

In [457]:
df.isnull().sum()

id                     0
title                  0
overview               0
genres                 0
keywords               0
release_date           0
director               0
director_popularity    0
movie_popularity       0
movie_imdb_id          0
movie_imdb_rating      0
num_votes              0
runtime_minutes        0
startYear              0
tags                   0
dtype: int64

In [455]:
startYear = df['startYear'].to_list()
release_date = df['release_date'].to_list()
startYear[4778] = 2024.0
release_date[4778] = '2024-04-28'
df['startYear'] = startYear
df['release_date'] = release_date

In [456]:
df.iloc[4778]

id                                                                683205
title                                                 The Legend Hunters
overview                             master story tomb raid raiders team
genres                                                  adventure action
keywords
release_date                                                  2024-04-28
director                                         [Li Yifan,  Simon West]
director_popularity                         [2.8369999999999997,  7.733]
movie_popularity                                                  22.026
movie_imdb_id                                                 tt10551126
movie_imdb_rating                                                    6.0
num_votes                                                              7
runtime_minutes                                                        0
startYear                                                         2024.0
tags                   adventure action  master story tomb raid raide...
Name: 4778, dtype: object

In [263]:
df.query(f"movie_imdb_id == 'tt22022452'")

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,runtime_minutes,startYear,tags
3,1022789,Inside Out 2,disgust feel fear room emotions sadness operat...,animation family adventure comedy,sadness disgust sequel computer-animation teen...,2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,96,2024.0,animation family adventure comedy sadness disg...

In [ ]:
df.sort_values(by='movie_popularity',ascending=False).head(20)

In [722]:
df.sample(50)

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,num_votes,runtime_minutes,startYear,tags
3927,985932,Virgin Forest,illegal photo thriving discovers rare flower m...,thriller crime drama,,2022-06-24,[Brillante MA Mendoza],[7.607],24.170,tt21078728,4.4,564,113,2022.0,"(thriller, crime, drama, , illegal, photo, th..."
7505,151368,Open Windows,refuses mouse computer favorite refuse view re...,thriller action crime,high-technology computer-screen found-footage ...,2014-07-04,[Nacho Vigalondo],[4.471],17.379,tt2409818,5.1,15196,100,2014.0,"(thriller, action, crime, high, -, technology,..."
3688,19542,The Red Shoes,drama charming stress art eventually romance c...,drama romance,dance new-love london england dance-performanc...,1948-09-06,"[Michael Powell, Emeric Pressburger]","[8.589, 3.545]",24.985,tt0040725,8.1,39971,135,1948.0,"(drama, romance, dance, new, -, love, london, ..."
2635,1441,The Contract,trip lawman dangerous peaceful escaping family...,drama action thriller crime,usa-president hitman fbi attempted-murder miss...,2006-04-05,[Bruce Beresford],[6.055],29.460,tt0445946,5.6,26288,96,2006.0,"(drama, action, thriller, crime, usa, -, presi..."
7253,199591,Penthouse North,reclusive boyfriend sadistic smooth photojourn...,thriller drama,hostage penthouse gangsters thriller,2013-04-17,[Joseph Ruben],[4.781],19.406,tt2055709,5.5,5942,90,2013.0,"(thriller, drama, hostage, penthouse, gangster..."
3670,2018,The Wedding Planner,wedding planner continues man arrangements san...,comedy romance,san-francisco california arranged-marriage wed...,2001-01-26,[Adam Shankman],[10.911],25.040,tt0209475,5.3,87794,103,2001.0,"(comedy, romance, san, -, francisco, californi..."
5997,211755,Hunter x Hunter: Phantom Rouge,dangerous killua opponent face troupe kurapika...,animation adventure fantasy action,adult-animation shounen anime,2013-01-12,[Yuzo Sato],[2.37],16.686,tt2918988,6.6,3313,97,2013.0,"(animation, adventure, fantasy, action, adult,..."
8267,557946,Last Looks,investigate cop woods solace private eccentric...,action crime thriller,private-investigator missing-person,2022-01-27,[Tim Kirkby],[2.23],16.489,tt9244554,5.8,12673,110,2022.0,"(action, crime, thriller, private, -, investig..."
4984,52449,Bad Teacher,dumps forced incompetent boob lazy teacher hat...,comedy,classroom manipulation teacher school middle-s...,2011-05-16,[Jake Kasdan],[12.5],21.547,tt1284575,5.7,214374,92,2011.0,"(comedy, classroom, manipulation, teacher, sch..."
4014,652722,In the Arms of an Assassin,levy raised forced assassin kill sanz payment ...,romance thriller,,2019-12-06,[Matías Moltrasio],[1.849],23.904,tt10080270,5.9,1465,106,2019.0,"(romance, thriller, , levy, raised, forced, a..."
495,999582,Babes,stand guide single pregnant friend leans woman...,comedy,,2024-05-17,[Pamela Adlon],[13.217],67.063,tt21276958,6.3,3609,104,2024.0,"(comedy, , stand, guide, single, pregnant, fr..."
9204,82657,Flight 7500,tokyo hour passengers international appears oc...,thriller horror mystery,supernatural flight ghost pacific--ocean,2014-05-16,[Takashi Shimizu],[10.695],15.628,tt1975159,4.8,17345,80,2014.0,"(thriller, horror, mystery, supernatural, flig..."
4992,308504,Last Knights,journey emperor honour destroyed leader band e...,action adventure,loyalty emperor castle sword-fight revenge hon...,2015-04-03,[Kazuaki Kiriya],[2.677],21.537,tt2493486,6.2,46123,115,2015.0,"(action, adventure, loyalty, emperor, castle, ..."
5632,14913,Boogeyman 2,health fear greatest facility attempts helples...,horror thriller,nightmare loss-of-loved-one shower bulimia gro...,2007-10-20,[Jeff Betancourt],[5.112],20.195,tt0900357,5.0,9107,93,2007.0,"(horror, thriller, nightmare, loss, -, of, -, ..."
2958,11281,Halloween II,stabs staff loomis myers favorite michael kill...,horror thriller,mask sheriff halloween sequel hospital holiday...,1981-10-30,[Rick Rosenthal],[6.083],27.966,tt0082495,6.5,103169,92,1981.0,"(horror, thriller, mask, sheriff, halloween, s..."
4578,11560,High Crimes,framed tells husband years accused believing m...,drama mystery thriller crime,based-on-novel-or-book court witness trial lov...,2002-04-05,[Carl Franklin],[6.6690000000000005],22.444,tt0257756,6.4,48882,115,2002.0,"(drama, mystery, thriller, crime, based, -, on..."
9393,39957,Burning Bright,autistic house heroine man beast loses college...,drama horror thriller,tiger autism hurricane animal-attack trapped,2010-08-17,[Carlos Brooks],[2.097],15.466,tt1244658,5.8,8078,89,2010.0,"(drama, horror, thriller, tiger, autism, hurri..."
5076,44244,Camp Rock 2: The Final Jam,competition featuring superstar newcomers gray...,comedy music tv-movie,summer-camp battle-of-the-bands camp singing s...,2010-09-17,[Paul Hoen],[3.23],21.327,tt1252380,5.2,21097,97,2010.0,"(comedy, music, tv, -, movie, summer, -, camp,..."
4542,11134,Police Story 3: Super Cop,kong female drug hong detective czar red count...,action crime thriller,martial-arts china police thailand prison-esca...,1992-07-04,[Stanley Tong],[7.632],22.531,tt0104558,7.0,24700,91,1992.0,"(action, crime, thriller, martial, -, arts, ch..."
7216,15981,Dead Leaves,crime food named earth penitentiary captured a...,animation comedy crime science-fiction,prison prisoner sexual-humor slapstick-comedy ...,2004-01-17,[Hiroyuki Imaishi],[7.041],17.720,tt0439533,7.1,4513,55,2004.0,"(animation, comedy, crime, science, -, fiction..."
1605,601,E.T. the Extra-Terrestrial,task earth elliot form terrestrial alien siste...,science-fiction adventure family fantasy,farewell space-marine operation flying-saucer ...,1982-06-11,[Steven Spielberg],[38.774],38.076,tt0083866,7.9,443070,115,1982.0,"(science, -, fiction, adventure, family, fanta..."
2877,17898,Silver Bullet,appearance tarker creature murders startled no...,horror,based-on-novel-or-book maine werewolf,1985-10-10,[Daniel Attias],[2.208],28.260,tt0090021,6.4,32091,95,1985.0,"(horror, based, -, on, -, novel, -, or, -, boo..."
6259,372519,The Ten Commandments: The Movie,moses book egypt exodus story people bible sla...,drama,,2016-01-28,[Alexandre Avancini],[6.538],19.070,tt5431016,3.1,1214,120,2016.0,"(drama, , moses, book, egypt, exodus, story, ..."
3280,2395,Asterix at the Olympic Games,obélix trick book rid team game irina princess...,fantasy adventure comedy family,colosseum wild-boar magic competition olympic-...,2008-01-30,"[Thomas Langmann, Frédéric Forestier]","[4.564, 6.101]",26.470,tt0463872,5.2,32978,116,2008.0,"(fantasy, adventure, comedy, family, colosseum..."
2897,3036,Mary Shelley's Frankenstein,promising regrets childbirth actions monster c...,drama horror science-fiction romance,experiment remake gothic-horror goth,1994-11-04,[Kenneth Branagh],[23.074],28.196,tt0109836,6.3,59864,123,1994.0,"(drama, horror, science, -, fiction, romance, ..."
2351,800158,The Killer,assassin international manhunt insists battles...,crime thriller,sniper new-york-city assassin airport paris fr...,2023-10-25,[David Fincher],[10.302],31.075,tt1136617,6.7,195758,118,2023.0,"(crime, thriller, sniper, new, -, york, -, cit..."
2568,11918,Superhero Movie,hourglass dragonfly rick enter riker aka goofy...,comedy action science-fiction,high-school superhero anti-hero parody dragonf...,2008-03-28,[Craig Mazin],[5.003],29.806,tt0426592,4.7,76980,75,2008.0,"(comedy, action, science, -, fiction, high, -,..."
8964,65945,Red Faction: Origins,saga dangerous family stars led rock thq lloyd...,science-fiction,planet-mars 22nd-century,2011-06-04,[Michael Nankin],[2.63],15.834,tt1693872,5.1,3883,88,2011.0,"(science, -, fiction, planet, -, mars, 22nd, -..."
3792,40264,Vampires Suck,romantic vampire controlling issues boys frien...,comedy fantasy,high-school vampire parody spoof prom horror-s...,2010-08-18,"[Jason Friedberg, Aaron Seltzer]","[6.038, 5.796]",24.573,tt1666186,3.4,52025,82,2010.0,"(comedy, fantasy, high, -, school, vampire, pa..."
3729,7347,Elite Squad,intends dangerous risks lodged janeiro nearby ...,drama action crime,drug-dealer police-brutality slum war-on-drugs...,2007-10-12,[José Padilha],[2.827],24.809,tt0861739,8.0,111997,115,2007.0,"(drama, action, crime, drug, -, dealer, police..."
2941,227,The Outsiders,greasers chain socs ponyboy tension johnny poo...,crime drama,"street-gang based-on-novel-or-book ""childrens-...",1983-03-25,[Francis Ford Coppola],[8.629],28.033,tt0086066,7.0,100170,91,1983.0,"(crime, drama, street, -, gang, based, -, on, ..."
3011,618344,Justice League Dark: Apokolips War,heroes earth inhabitants decimated tyrant stra...,animation action science-fiction,superhero based-on-comic dc-animated-movie-uni...,2020-05-05,"[Matt Peters, Christina Sotta]","[5.864, 4.059]",27.681,tt11079148,7.7,27456,90,2020.0,"(animation, action, science, -, fiction, super..."
4768,13937,Raising Cain,children performed husband neighborhood psycho...,thriller crime horror,child-abuse kidnapping detective attempted-mur...,1992-08-07,[Brian De Palma],[9.965],22.057,tt0105217,6.1,17702,92,1992.0,"(thriller, crime, horror, child, -, abuse, kid..."
603,545611,Everything Everywhere All at Once,adventure chinese immigrant led aging connecti...,action adventure science-fiction,mother martial-arts kung-fu philosophy generat...,2022-03-24,"[Daniel Scheinert, Daniel Kwan]","[5.811, 4.68]",61.258,tt6710474,7.8,550281,139,2022.0,"(action, adventure, science, -, fiction, mothe..."
8190,641,Requiem for a Dream,deep drug addictions shattered coney island in...,crime drama,drug-dealer corruption drug-abuse unsociabilit...,2000-10-06,[Darren Aronofsky],[11.911],16.588,tt0180093,8.3,912336,102,2000.0,"(crime, drama, drug, -, dealer, corruption, dr..."
6979,483,Wild at Heart,ripley troubles lula serving kill shared despe...,crime thriller romance,witch hotel-room based-on-novel-or-book hitman...,1990-08-17,[David Lynch],[15.989],18.031,tt0100935,7.2,102396,125,1990.0,"(crime, thriller, romance, witch, hotel, -, ro..."
3453,10982,Hoodwinked!,investigate involving hood book winds wolf gra...,animation comedy family crime,wolf investigation suspicion little-red-riding...,2005-12-16,"[Todd Edwards, Tony Leech, Cory Edwards]","[1.9300000000000002, 2.766, 4.495]",25.818,tt0443536,6.5,67255,80,2005.0,"(animation, comedy, family, crime, wolf, inves..."
4544,19415,Summer Lovers,nature michael paris pappas archaeological gre...,drama romance comedy,infidelity jealousy love-triangle sexuality gr...,1982-07-16,[Randal Kleiser],[4.564],22.525,tt0084737,5.8,4564,98,1982.0,"(drama, romance, comedy, infidelity, jealousy,..."
147,1291559,Drawing Closer,terminally girl live finds meaning life joy ye...,romance drama,terminal-illness,2024-06-26,[Takahiro Miki],[6.127],117.013,tt31078761,7.6,1471,118,2024.0,"(romance, drama, terminal, -, illness, termina..."
1135,10867,Malena,living small boy italian stricken wwii discove...,drama,jealousy sicily italy widow world-war-ii longi...,2000-03-16,[Giuseppe Tornatore],[9.852],45.383,tt0213847,7.4,113862,108,2000.0,"(drama, jealousy, sicily, italy, widow, world,..."
8888,200481,The Blue Umbrella,dripping pipes sound gutters evening commute r...,animation romance,rain anthropomorphism umbrella selective-color...,2013-02-12,[Saschka Unseld],[1.826],15.896,tt2616880,7.5,11349,7,2013.0,"(animation, romance, rain, anthropomorphism, u..."
6318,166981,Chastity Bites,finally educator paper believed today america ...,horror comedy,high-school feminism serial-killer reporter bl...,2013-06-01,[John V. Knowles],[0.259],18.978,tt2145637,4.6,1066,93,2013.0,"(horror, comedy, high, -, school, feminism, se..."
7391,10145,The Forgotten,stunned cope man years son sanity experience t...,thriller drama mystery science-fiction,airplane loss-of-loved-one delusion motel grie...,2004-09-24,[Joseph Ruben],[4.781],17.514,tt0356618,5.8,68745,91,2004.0,"(thriller, drama, mystery, science, -, fiction..."
6110,8848,The Bank Job,heist underworld thieves lloyds family implica...,thriller crime drama,infidelity mannequin wife photography subway v...,2008-02-28,[Roger Donaldson],[5.773],19.323,tt0200465,7.2,190621,111,2008.0,"(thriller, crime, drama, infidelity, mannequin..."
6545,1229958,"Lover, Stalker, Killer",online twisting romantic dating deadly documen...,documentary crime,true-crime murder-investigation online-dating ...,2024-02-09,[Sam Hobkinson],[3.049],18.641,tt30852970,7.0,11787,90,2024.0,"(documentary, crime, true, -, crime, murder, -..."
6888,1404,Ae Fond Kiss...,love falls irish man family schoolteacher upse...,drama romance,"muslim ""love-of-ones-life"" tradition glasgow s...",2004-02-13,[Ken Loach],[8.771],18.147,tt0380366,7.1,7348,104,2004.0,"(drama, romance, muslim, "", love, -, of, -, on..."
6433,15142,Dream a Little Dream,experiment jerk contact working accident colem...,fantasy comedy romance,dream body-swap,1989-03-03,[Marc Rocco],[3.462],18.811,tt0097236,5.8,7962,114,1989.0,"(fantasy, comedy, romance, dream, body, -, swa..."
3879,175168,Rape Zombie: Lust of the Dead,momoko stand tokyo sex seek housewife tamae ka...,comedy horror,rape zombie softcore,2012-07-13,[Naoyuki Tomomatsu],[6.371],24.296,tt2271565,3.7,1286,73,2012.0,"(comedy, horror, rape, zombie, softcore, momok..."
5086,20544,Something the Lord Made,vivien alfred heart relationship thomas surger...,tv-movie drama,"friendship mentor biography ""man-of-ones-dream...",2004-05-30,[Joseph Sargent],[16.329],21.293,tt0386792,8.1,15758,110,2004.0,"(tv, -, movie, drama, friendship, mentor, biog..."
3690,16962,Barbie Fairytopia: Magic of the Rainbow,intends fellow dancing performing annual fairi...,animation family fantasy romance,fairy based-on-toy,2007-03-13,[William Lau],[4.744],24.984,tt1007920,6.2,3301,75,2007.0,"(animation, family, fantasy, romance, fairy, b..."

In [21]:
def search_movie(col,word):
    results = []
    for i,movie_title in enumerate(df[col]):
        if word in movie_title:
            results.append(i)
    return df.iloc[results]

In [32]:
search_movie('title','Smile')

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,num_votes,runtime_minutes,tags,startYear
947,882598,Smile,traumatic involving rose occurrences bizarre s...,horror mystery thriller,suicide new-jersey post-traumatic-stress-disor...,2022-09-23,[Parker Finn],[3.44],49.440,tt15474916,6.5,177428,115,"(horror, mystery, thriller, suicide, new, -, j...",2022
3058,108450,The Smile of the Fox,baron passionate cop escape pimp fascinated co...,thriller drama romance,romance argentina erotic thriller,1992-05-22,[Sergio Martino],[3.024],27.424,tt0111222,4.4,659,82,"(thriller, drama, romance, romance, argentina,...",1992
5271,11820,Mona Lisa Smile,society inspires embraces college joan art ucl...,drama history romance,massachusetts art-school inspiration feminist ...,2003-12-19,[Mike Newell],[4.8870000000000005],20.896,tt0304415,6.6,92673,117,"(drama, history, romance, massachusetts, art, ...",2003
8995,13168,Smiley Face,including cupcakes start day series roommate t...,comedy,drug-dealer hippie roommate flashback stoned g...,2007-11-16,[Gregg Araki],[3.674],15.811,tt0780608,5.8,19433,85,"(comedy, drug, -, dealer, hippie, roommate, fl...",2007
9446,59300,Final Fantasy VII: On the Way to a Smile - Epi...,tells joining regenesis prior years denzel mid...,animation fantasy,based-on-video-game,2009-04-16,[Shinji Ishihira],[2.259],15.418,tt1980204,6.7,372,28,"(animation, fantasy, based, -, on, -, video, -...",2009

# Building Models

In [9]:
res = req.get('http://localhost:8080/get/all')

In [10]:
df = pd.DataFrame().from_dict(res.json())

In [11]:
df.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,num_votes,runtime_minutes,tags
0,365177,Borderlands,key dangerous protect heroes alliance power te...,action science-fiction comedy adventure thriller,outlaw based-on-video-game unlikely-friendship...,2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,101,action science-fiction comedy adventure thrill...
1,533535,Deadpool & Wolverine,flexible listless existential wilson reluctant...,action comedy science-fiction,hero superhero anti-hero mutant breaking-the-f...,2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,128,action comedy science-fiction hero superhero a...
2,917496,Beetlejuice Beetlejuice,lydia daughter afterlife generations family ac...,comedy horror fantasy,afterlife haunted-house sequel paranormal teen...,2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,105,comedy horror fantasy afterlife haunted-house ...
3,1022789,Inside Out 2,disgust feel fear room emotions sadness operat...,animation family adventure comedy,sadness disgust sequel computer-animation teen...,2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,96,animation family adventure comedy sadness disg...
4,970347,The Killer,refuses feared zee finds murder woman criminal...,action thriller crime,,2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,126,action thriller crime refuses feared zee find...

In [12]:
df['startYear'] = pd.to_datetime(df['release_date']).dt.year

In [13]:
nlp = spacy.load('en_core_web_lg')

## Model Recommedations

In [ ]:
imdb_id = 'tt0119282'
df.query(f"movie_imdb_id == '{imdb_id}'")

In [28]:
tags = df.tags.to_list()

In [16]:
def nlp_transomation(tags):
    nlp_tags = []
    for tag in tqdm(tags):
        nlp_tag = nlp(f'{tag}')
        nlp_tags.append(nlp_tag)
    return nlp_tags

In [513]:
df['tags'] = nlp_tags

In [13]:
df.tags.dtype

dtype('O')

In [29]:
df.tags = nlp_transomation(tags)

100%|█████████████████████████████████████████████████████████████████████████████| 9509/9509 [00:44<00:00, 215.78it/s]

In [18]:
df_copy = df.copy()

In [19]:
genres = df.genres.to_list()
df.tags = nlp_transomation(genres)

100%|██████████████████████████████████████████████████████████████████████████████| 9509/9509 [01:58<00:00, 80.27it/s]

In [55]:
def recommendations_for(imdb_id, year = 2000, least_rate = 5, freq = 10):
    mv_df = df.query(f'startYear >= {year} & movie_imdb_rating >= {least_rate}').reset_index().drop(columns = 'index')
    movie =  mv_df.query(f"movie_imdb_id == '{imdb_id}'")
    title = movie.title.values[0]
    year = movie.startYear.values[0]
    scores = []
    indices = range(mv_df.shape[0])
    
    print(f"Best recommendation for `{title} {int(year)}` is:")
    movie_tags = mv_df.query(f"movie_imdb_id == '{imdb_id}'")['tags'].values[0]
    
    for index in indices:
        scores.append(np.round(np.ceil(movie_tags.similarity(mv_df.iloc[index].tags) * 1000) / 1000,2))
        
    recommends = pd.DataFrame({'imdb_id':mv_df.movie_imdb_id.values,
                                'title':mv_df.title.values,
                                'startYear':mv_df.startYear.values,
                                'score':scores,
                                'pop': (scores) + (mv_df.movie_imdb_rating / 3e1) + (mv_df.num_votes / 3.6e7) + (mv_df.startYear / 5e2),
                                'rating':mv_df.movie_imdb_rating,
                                'popularity':mv_df.movie_popularity,
                                'num_votes':mv_df.num_votes,
                                'genre':mv_df.genres 
                              })
    
    recommends.drop(recommends.query('score >= 1.0').index,inplace = True)
    recommends = recommends.sort_values(by=['pop','startYear'],ascending = False).reset_index().drop(columns = ['index','pop'])
    return recommends.head(freq) ,

In [57]:
recom = recommendations_for('tt15474916',freq=50)
recom

Best recommendation for `Smile 2022` is:

,imdb_id,title,startYear,score,rating,popularity,num_votes,genre
0,tt28015403,Heretic,2024,0.96,8.1,17.396,47,horror thriller
1,tt0209144,Memento,2000,0.96,8.4,23.738,1340807,mystery thriller
2,tt1130884,Shutter Island,2010,0.92,8.2,63.348,1487954,drama thriller mystery
3,tt4972582,Split,2017,0.96,7.3,57.768,568042,horror thriller
4,tt1457767,The Conjuring,2013,0.96,7.5,119.215,565411,horror thriller
5,tt1189073,The Skin I Live In,2011,0.97,7.6,22.621,168611,drama horror mystery thriller
6,tt2267998,Gone Girl,2014,0.92,8.1,64.879,1085821,mystery thriller drama
7,tt1588170,I Saw the Devil,2010,0.96,7.8,23.709,149544,thriller horror
8,tt5215952,The Wailing,2016,0.96,7.4,29.167,85295,horror mystery
9,tt7144666,The Black Phone,2022,0.96,6.9,47.898,207459,horror thriller
10,tt1937149,The Body,2012,0.96,7.6,18.124,73673,thriller mystery
11,tt14858658,Blink Twice,2024,0.96,6.9,121.957,16467,mystery thriller
12,tt5473412,Kill,2024,0.96,6.9,36.476,43,thriller horror
13,tt4160708,Don't Breathe,2016,0.96,7.1,39.594,307354,horror thriller
14,tt16300962,When Evil Lurks,2023,0.96,6.9,56.875,41627,horror thriller
15,tt8772262,Midsommar,2019,0.95,7.1,46.067,420429,horror drama mystery
16,tt6857112,Us,2019,0.96,6.8,30.640,349971,horror thriller
17,tt26470109,Oddity,2024,0.96,6.7,233.654,14000,horror mystery
18,tt1259521,The Cabin in the Woods,2012,0.96,7.0,29.759,458440,horror mystery
19,tt0947798,Black Swan,2010,0.92,8.0,38.948,836938,drama thriller horror
20,tt27489557,Abigail,2024,0.96,6.6,102.280,67121,horror thriller
21,tt13403046,Fresh,2022,0.96,6.7,28.359,78412,horror thriller
22,tt21807222,Saw X,2023,0.96,6.6,56.905,81898,horror thriller
23,tt30516366,Chime,2024,0.96,6.6,17.095,843,horror thriller
24,tt5606664,Doctor Sleep,2019,0.94,7.3,30.072,222772,horror thriller fantasy
25,tt9701940,Fear Street: 1978,2021,0.96,6.7,18.693,78708,mystery horror
26,tt9731534,The Night House,2021,0.97,6.4,20.427,69216,drama horror mystery thriller
27,tt23736044,Monster,2023,0.92,7.8,54.162,27679,mystery thriller drama
28,tt13345606,Evil Dead Rise,2023,0.96,6.5,72.045,144697,horror thriller
29,tt1772250,The Hidden Face,2011,0.96,7.3,25.162,46925,thriller mystery
30,tt6079516,I See You,2019,0.96,6.8,19.277,68530,horror thriller
31,tt1038988,[REC],2007,0.96,7.4,30.683,200361,horror mystery
32,tt4857264,The Invisible Guest,2017,0.92,8.0,38.892,195839,drama mystery thriller
33,tt14527836,Recalled,2021,0.96,6.7,19.528,5446,mystery thriller
34,tt14253846,Speak No Evil,2022,0.96,6.6,44.336,43922,horror thriller
35,tt1139328,The Ghost Writer,2010,0.96,7.2,21.583,171885,thriller mystery
36,tt27534307,Speak No Evil,2024,0.96,6.5,317.227,355,horror thriller
37,tt30319570,Sakaratul Maut,2024,0.96,6.5,25.074,44,horror thriller
38,tt3235888,It Follows,2015,0.96,6.8,50.500,275889,horror mystery
39,tt2316411,Enemy,2014,0.96,6.9,28.506,219215,thriller mystery
40,tt1437358,Sleep Tight,2011,0.96,7.2,16.061,47361,thriller horror
41,tt3289956,The Autopsy of Jane Doe,2016,0.96,6.8,59.919,144295,horror mystery
42,tt2873282,Red Sparrow,2018,0.96,6.6,25.027,204038,thriller mystery
43,tt26674818,Tatami,2024,0.92,7.6,27.562,944,thriller drama mystery
44,tt0460829,Inland Empire,2006,0.98,6.8,24.550,63315,thriller mystery fantasy horror
45,tt14537248,Nefarious,2023,0.96,6.4,23.496,30103,horror thriller
46,tt21979910,The Passenger,2023,0.96,6.4,22.142,7813,horror thriller
47,tt13446168,The Medium,2021,0.96,6.5,25.796,14045,horror thriller
48,tt26736843,The Watchers,2024,0.98,5.7,129.839,34469,horror fantasy mystery thriller
49,tt5308322,Happy Death Day,2017,0.96,6.6,18.306,167548,horror mystery comedy thriller

In [60]:
df.drop('id',axis = 1).select_dtypes(np.number).corr()

,movie_popularity,movie_imdb_rating,num_votes,runtime_minutes,startYear
movie_popularity,1.000000,0.011942,0.134373,0.048322,0.109085
movie_imdb_rating,0.011942,1.000000,0.374961,0.285632,-0.270889
num_votes,0.134373,0.374961,1.000000,0.296807,-0.037456
runtime_minutes,0.048322,0.285632,0.296807,1.000000,-0.039131
startYear,0.109085,-0.270889,-0.037456,-0.039131,1.000000

In [63]:
recom.select_dtypes(np.number).corr()['score']

startYear     0.036859
score         1.000000
rating       -0.620459
popularity    0.039075
num_votes    -0.446281
Name: score, dtype: float64