# Install additional libraries

In [1]:
%pip install IMDbPY

Requirement already satisfied: IMDbPY in c:\users\lenovo\miniconda3\lib\site-packages (2022.7.9)
Requirement already satisfied: cinemagoer in c:\users\lenovo\miniconda3\lib\site-packages (from IMDbPY) (2023.5.1)
Requirement already satisfied: SQLAlchemy in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (2.0.31)
Requirement already satisfied: lxml in c:\users\lenovo\miniconda3\lib\site-packages (from cinemagoer->IMDbPY) (4.6.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\miniconda3\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

# Import Libraries

In [1]:
# Data gathering libraries
from imdb import IMDb
import requests
import gzip as gz
import json

In [2]:
# Data Analysis Libraries
import pandas as pd
import numpy as np

In [3]:
# Visualization libaries
import matplotlib.pyplot as plt
import seaborn as sns

In [125]:
# NLP libraies
import nltk
from nltk.tokenize import word_tokenize
import spacy
import fasttext as ft

In [128]:
# install punctuation tool kit
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [134]:
ft.load_model('../datasets/cc.en.300.bin')

ValueError: ../datasets/cc.en.300.vec has wrong file format!

In [6]:
# additional libraries
import pprint
from tqdm import tqdm
import pickle as pkl
import warnings
warnings.filterwarnings('ignore')
import sys

# Data Gathering

## Retriving Data from tmdb API

In [8]:
discover_urls = [f"https://api.themoviedb.org/3/discover/movie?include_adult=true&include_video=false&language=en-US&page={i}&sort_by=popularity.desc" for i in range(1,501)]

genre_url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

keyword_url = "https://api.themoviedb.org/3/movie/movie_id/keywords"

details_url = "https://api.themoviedb.org/3/movie/movie_id?language=en-US"

credit_url = "https://api.themoviedb.org/3/movie/movie_id/credits?language=en-US"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MDM0ZGRiZTc2MjBlNDA5YmIyZTFjYWY4YTQzM2JjOSIsInN1YiI6IjY0ZmY0NjA1ZWIxNGZhMDBhZGE1ZDU4ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jDadAw2N_wZERgQvHIqf-7XGKyORY1MQiw8DlIC09H8"
}

In [9]:
movies_results = []
for discover_url in tqdm(discover_urls):
    res = requests.get(discover_url, headers=headers)
    movies_results.extend(res.json()['results'])

100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [04:01<00:00,  2.07it/s]

In [10]:
genre_response = requests.get(genre_url,headers=headers)
genre_results = genre_response.json()['genres']

In [11]:
movies = {
    "id" : [],
    "title": [],
    "overview": [],
    "genres": [],
    "keywords":[],
    "release_date":[],
    "director": [],
    "director_popularity": [],
    "movie_popularity":[],
    "movie_imdb_id": []
}

In [12]:
for movie in tqdm(movies_results):
    movies['id'].append(movie['id'])
    movies['title'].append(movie['title'])
    movies['genres'].append(movie['genre_ids'])

100%|████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 535431.67it/s]

In [13]:
movies['keywords'] = []
for movie_id in tqdm(movies['id']):
    keyword_response = requests.get(url = keyword_url.replace("movie_id",str(movie_id)),
                                    headers = headers)
    keywords = keyword_response.json()['keywords']
    movie_keyword_names = []
    for keyword in keywords:
        movie_keyword_names.append(keyword['name'])
    movies['keywords'].append(movie_keyword_names)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [46:40<00:00,  3.57it/s]

In [14]:
movies['overview'] = []
movies['release_date'] = []
movies['movie_imdb_id'] = []
movies['movie_popularity'] = []
for movie_id in tqdm(movies['id']):
  details_response = requests.get(url = details_url.replace("movie_id",str(movie_id)),
                                  headers = headers)
  overview = details_response.json()['overview']
  release_date = details_response.json()['release_date']
  imdb_id = details_response.json()['imdb_id']
  popularity = details_response.json()['popularity']
  movies['overview'].append(overview)
  movies['release_date'].append(release_date)
  movies['movie_imdb_id'].append(imdb_id)
  movies['movie_popularity'].append(popularity)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [37:36<00:00,  4.43it/s]

In [16]:
movies['director'] = []
movies['director_popularity'] = []
for movie_id in tqdm(movies['id']):
  credit_response = requests.get(url = credit_url.replace("movie_id",str(movie_id)),
                                 headers = headers)
  crew = credit_response.json()['crew']
  director_names = []
  director_popularity = []
  for crew_credit in crew:
    if crew_credit['job'] == "Director":
      director_names.append(crew_credit['name'])
      director_popularity.append(crew_credit['popularity'])
  movies['director'].append(director_names)
  movies['director_popularity'].append(director_popularity)

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [22:29<00:00,  7.41it/s]

In [17]:
for g_index in tqdm(range(len(movies['genres']))):
    for g_result in genre_results:
        movies['genres'][g_index] = (
            list(
            map(
                lambda x: str(x).replace(str(g_result['id']), g_result['name']),
                movies['genres'][g_index]
                )
            )
         )

100%|█████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 23324.38it/s]

In [18]:
for key,value in movies.items():
  print(key,'=>',len(value))

id => 10000
title => 10000
overview => 10000
genres => 10000
keywords => 10000
release_date => 10000
director => 10000
director_popularity => 10000
movie_popularity => 10000
movie_imdb_id => 10000

In [20]:
# movies.pop('movie_imdb_rating')
df_movies = pd.DataFrame(movies)

In [22]:
df_movies.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948

In [23]:
df_movies.to_json("movies_1.json")
# df_movies.T.to_json("movies_2.json")

In [7]:
# df_movies = pd.read_csv('movies.csv',lineterminator='\n').iloc[:,1:]
df_movies = pd.read_json('movies_1.json')

In [8]:
df_movies.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948

In [9]:
df_movies[df_movies['movie_imdb_id'].isnull()]

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
66,482600,Japanese Mom,"""Innocent face, D-cup breasts and perfect inte...","[Romance, Drama]",[softcore],2017-02-09,[Kim Moo-won],[2.911],213.021,None
78,1338575,M – La Última Esperanza,,"[Adventure, Drama, Science Fiction]",[],2023-01-04,[Vardan Tozija],[0.49],196.980,None
81,1190586,Leggings Mania,Jeong-hee was living with a man due to a de fa...,"[Drama, Romance]","[softcore, nudity]",2023-07-13,[Richard Kim],[7.877],197.521,None
155,1285810,Forbidden Immoral Sex 3: Too Young Stepmother,,[Drama],[stepmother],2018-05-07,[Sadao Sadaoka],[0.98],133.976,None
218,1149913,TOGEFILM - Mei Mei,,"[Drama, Romance]",[],2023-04-06,[],[],112.576,None
...,...,...,...,...,...,...,...,...,...,...
9793,1177963,No vayan!!: La película,This is the story of two inseparable cousins w...,"[Comedy, History, Family]",[],2023-11-23,[],[],15.525,None
9797,1336214,THE IMPACT | Groundbreaking Documentary,Discover the unsettling truths behind the worl...,"[Documentary, History, TV Movie, War]","[mind control, neo-nazism, society, totalitari...",2024-07-12,[],[],15.524,None
9815,1300527,Heavens,,"[Horror, Thriller]","[dream, nightmare, heavens]",2024-09-10,[Alberto Meleleo],[0.001],15.513,None
9820,1340881,"4EVE Concert ""NOW OR NEVER"" Live at Impact Arena",Thai pop superstars 4EVE dazzle their fans wit...,[Music],[],2024-08-30,[],[],15.507,None
9958,719128,Idol Sex: LA Korean Women,Typhoon and Taeyang brothers are sharing. The ...,"[Romance, Drama]","[softcore, erotic, melodrama]",2020-06-18,[Jeong Mi-na],[3.17],15.393,None

In [10]:
df_movies[df_movies['movie_imdb_id'] == '']

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id
235,387824,Mom's Friend,"Seong Soo, a twenty years old boy, decided to ...","[Drama, Romance]",[softcore],2015-08-20,[Myeong Seok Hwan],[4.299],98.486,
432,60957,田中瞳 爆乳Jの衝撃,,[],[],2007-11-08,[],[],77.370,
2015,387822,Comic Series,Episode 1. Teasing the husband\r A man and a w...,"[Romance, Comedy]",[softcore],2016-02-25,[Ahn Il-hwan],[0.732],21.076,
2272,440617,Family Reconstruction,Gwang-sik is a single father with a son and Ha...,"[Romance, Drama]",[softcore],2017-02-14,[],[],32.675,
2575,452251,Beauty Salon: Special Service,A legendary beauty salon that is sure to becom...,"[Romance, Drama]","[sister, beauty salon, prostitution, threesome...",2016-12-29,[Lee Ri-dan],[7.557],30.680,
2935,405817,Young Mother: The Original,I had a dream...sleeping with you and Hwa-yeon...,"[Drama, Romance]","[softcore, complicated relationships]",2016-06-23,[Jeong Do-soo],[3.099],28.757,
3375,409276,What a Good Secretary Wants,The silent secret of the perfect woman. Geniu...,"[Romance, Drama]","[secretary, softcore]",2016-05-20,[Kim Hyo-jae],[1.079],26.908,
3708,431803,Kabaneri of the Iron Fortress: Life That Burns,"In the midst of an industrial revolution, the ...","[Animation, Drama, Action, Science Fiction]","[samurai, post-apocalyptic future, steampunk, ...",2017-01-07,[Tetsuro Araki],[4.471],25.700,
3761,397469,New Folder 2,"Ho-jae has the building, the house, the fancy ...",[Drama],[softcore],2015-10-23,[Hwang Sang-won],[1.772],25.509,
4006,15257,Hulk vs. Wolverine,Department H sends in Wolverine to track down ...,"[Animation, Action, Science Fiction, Adventure...","[superhero, mutant, based on comic, norse myth...",2009-01-27,[Frank Paur],[1.653],24.656,
4477,592742,Be My Master,"Meguro, who works for the advertising design c...",[Drama],[pink film],2018-09-29,[Hideo Jojo],[10.001],23.343,
4528,409387,Sex: A Relationship and Not Marriage,The life story of a woman who doesn't want to ...,"[Romance, Drama]",[softcore],2016-04-19,[Jo Kyeong-hoon-I],[0.9590000000000001],23.217,
6610,418827,Sister's Younger Husband,A sexy brother-in-law approached her? And he’s...,"[Comedy, Drama, Romance]","[softcore, complicated relationships]",2016-10-11,[Park Eun-ho],[0.366],19.074,
6799,357458,Young Mother: What's Wrong With My Age?,"Father, son and even grandson, are all mesmeri...","[Comedy, Romance]",[],2015-04-30,[Kim Jong-il],[1.278],18.800,
7748,376858,Boarding House 2,Joon-hyeok is preparing to pass the exam for 9...,[Romance],[softcore],2016-01-07,[Jeong Tae-ryeong],[0.741],17.559,
8166,460104,Young Lady,Joon-seok and Soo-yeon are 3 years married. Th...,"[Comedy, Drama, Romance]",[],2015-09-10,[Lee Se-jong],[0.001],17.112,
9779,101907,Hulk vs. Thor,"For ages, Odin has protected his kingdom of As...","[Action, Animation, Fantasy, Science Fiction]","[fight, superhero, based on comic, norse mytho...",2009-01-27,[Sam Liu],[3.341],15.537,
9801,117691,Gangs of Wasseypur - Part 1,"In 1970s India, Sardar Khan vows to take reven...","[Action, Thriller, Crime]","[mafia, gang, coal mining]",2012-06-22,[Anurag Kashyap],[10.461],15.522,

In [11]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   title                10000 non-null  object
 2   overview             10000 non-null  object
 3   genres               10000 non-null  object
 4   keywords             10000 non-null  object
 5   release_date         10000 non-null  object
 6   director             10000 non-null  object
 7   director_popularity  10000 non-null  object
 8   movie_popularity     10000 non-null  float64
 9   movie_imdb_id        9770 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 859.4+ KB

In [12]:
df_movies.drop(df_movies[(df_movies['movie_imdb_id'] == '') | (df_movies['movie_imdb_id'].isnull())].index,inplace=True)

In [13]:
df_movies.reset_index(inplace=True)
df_movies.drop(columns=['index'],inplace=True)

In [14]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   9752 non-null   int64
 1   title                9752 non-null   object
 2   overview             9752 non-null   object
 3   genres               9752 non-null   object
 4   keywords             9752 non-null   object
 5   release_date         9752 non-null   object
 6   director             9752 non-null   object
 7   director_popularity  9752 non-null   object
 8   movie_popularity     9752 non-null   float64
 9   movie_imdb_id        9752 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 762.0+ KB

## Filling missing Values

In [15]:
def get_director_name_and_popularity(id):
    if 'director' in (IMDb().get_movie(id).data.keys()):
        director_name = (IMDb()
                        .get_movie(id)
                        .data['director'][0]
                        .data['name']
        )
        url = ('https://api.themoviedb.org/3/search/person?query={}&include_adult=false&language=en-US&page=1'
                .format(director_name.strip().replace(" ","%20"))
              )

        results = (requests
                      .get(url,headers=headers)
                      .json()['results']
        )

        if len(results) > 0:
            popularity = results[0]['popularity']
        else:
            popularity = 0.0
            
    else:
          director_name = '-'
          popularity = 0.0
          
    return {'director_name':director_name,
                'director_popularity':popularity}

In [18]:
director_names = []
director_popularity = []
for index in tqdm(df_movies.index):
  if df_movies.iloc[index]['director'] == []:
    director_information = get_director_name_and_popularity(df_movies.iloc[index]['movie_imdb_id'][2:])
    director_names.append(director_information['director_name'])
    director_popularity.append(director_information['director_popularity'])
  else:
    director_names.append(df_movies.iloc[index]['director'])
    director_popularity.append(df_movies.iloc[index]['director_popularity'])

df_movies['director'] = director_names
df_movies['director_popularity'] = director_popularity

100%|█████████████████████████████████████████████████████████████████████████████| 9752/9752 [01:29<00:00, 108.38it/s]

## Integrate data from IMDb Bulk Dataset

In [22]:
ratings = pd.read_csv(gz.open("datasets/title.ratings.tsv.gz"),sep="\t")
ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2084
1  tt0000002            5.6       281
2  tt0000003            6.5      2086
3  tt0000004            5.4       182
4  tt0000005            6.2      2820

In [23]:
basics = pd.read_csv(gz.open("datasets/title.basics.tsv.gz"),delimiter='\t')

In [24]:
imdb_genres = basics.genres

In [25]:
basics.drop(columns=['genres'],inplace = True)

In [26]:
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,5
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1

In [ ]:
principals = pd.read_csv(gz.open("datasets/title.principals.tsv.gz"),sep='\t',encoding='utf-8',lineterminator='\n')

In [ ]:
principals.head()

In [27]:
df_1 = pd.merge(df_movies,ratings,how='inner',right_on='tconst',left_on = 'movie_imdb_id').drop(columns='tconst')

In [28]:
df_1.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709

In [29]:
df_2 = pd.merge(df_1,basics,how='inner',right_on='tconst',left_on='movie_imdb_id').drop(columns = ["tconst"])

In [30]:
df_2.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure, T...","[outlaw, based on video game, unlikely friends...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, breaking ...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranormal,...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animation,...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [31]:
sys.getsizeof(df_2)

13783197

In [32]:
df_2.to_csv('movies_df.csv')

# Dealing with DataBase

## Data Base API

In [43]:
movies_df = pd.read_csv('../datasets/movies_df.csv')

In [44]:
movies_df.head()

,Unnamed: 0,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,0,365177,Borderlands,"Returning to her home planet, an infamous boun...","['Action', 'Science Fiction', 'Comedy', 'Adven...","['outlaw', 'based on video game', 'unlikely fr...",2024-08-07,['Eli Roth'],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"['Action', 'Comedy', 'Science Fiction']","['hero', 'superhero', 'anti hero', 'mutant', '...",2024-07-24,['Shawn Levy'],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","['Comedy', 'Horror', 'Fantasy']","['afterlife', 'haunted house', 'sequel', 'para...",2024-09-04,['Tim Burton'],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"['Animation', 'Family', 'Adventure', 'Comedy']","['sadness', 'disgust', 'sequel', 'computer ani...",2024-06-11,['Kelsey Mann'],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","['Action', 'Thriller', 'Crime']",[],2024-08-22,['John Woo'],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [45]:
movies_df['genres'].iloc[1]

"['Action', 'Comedy', 'Science Fiction']"

In [46]:
for col in ['genres','keywords','director','director_popularity']:
    movies_df[col] = movies_df[col].apply(lambda x: x.replace("[","").replace("]","").replace("'","").split(","))

In [47]:
movies_df.head()

,Unnamed: 0,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure...","[outlaw, based on video game, unlikely frien...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,\N,101
1,1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, break...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,\N,128
2,2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranorm...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,\N,105
3,3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animati...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,\N,96
4,4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,\N,126

In [48]:
movies_df['endYear'] = movies_df['endYear'].replace({'\\N':'-'})

In [49]:
movies_df.drop('Unnamed: 0',axis = 1, inplace = True)

In [50]:
movies_df.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure...","[outlaw, based on video game, unlikely frien...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,23064,movie,Borderlands,Borderlands,0,2024,-,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, break...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,275259,movie,Deadpool & Wolverine,Deadpool & Wolverine,0,2024,-,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranorm...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,25446,movie,Beetlejuice Beetlejuice,Beetlejuice Beetlejuice,0,2024,-,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animati...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,126369,movie,Inside Out 2,Inside Out 2,0,2024,-,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,6709,movie,The Killer,The Killer,0,2024,-,126

In [120]:
requests.delete('http://localhost:8000/delete',{'query':{}})

## Inserting Data

In [52]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9585 entries, 0 to 9584
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   9585 non-null   int64
 1   title                9585 non-null   object
 2   overview             9573 non-null   object
 3   genres               9585 non-null   object
 4   keywords             9585 non-null   object
 5   release_date         9584 non-null   object
 6   director             9585 non-null   object
 7   director_popularity  9585 non-null   object
 8   movie_popularity     9585 non-null   float64
 9   movie_imdb_id        9585 non-null   object
 10  averageRating        9585 non-null   float64
 11  numVotes             9585 non-null   int64
 12  titleType            9585 non-null   object
 13  primaryTitle         9585 non-null   object
 14  originalTitle        9585 non-null   object
 15  isAdult              9585 non-null   int64
 16  startYear            9585 non-null   int64
 17  endYear              9585 non-null   object
 18  runtimeMinutes       9585 non-null   object
dtypes: float64(2), int64(4), object(13)
memory usage: 1.4+ MB

In [53]:
movies_df['runtimeMinutes'].replace({'\\N':0},inplace=True)

In [54]:
movies_df['runtimeMinutes'] = movies_df['runtimeMinutes'].astype(int)

In [55]:
movies_df.rename(columns=
    {
        "averageRating": "movie_imdb_rating",
        "numVotes":"num_votes",
        "titleType": "title_type",
        "primaryTitle": "primary_title",
        "originalTitle": "original_title",
        "isAdult":"is_adult",
        "startYear":"start_year",
        "endYear":"end_year",
        "runtimeMinutes": "runtime_minutes"
    }
,inplace=True)

In [56]:
movies_documents = movies_df.drop(columns = ['num_votes','title_type','primary_title','original_title','is_adult','start_year','end_year']).T.to_dict()

In [57]:
first_it = movies_documents[0]

In [58]:
first_it

{'id': 365177,
 'title': 'Borderlands',
 'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
 'genres': ['Action',
  ' Science Fiction',
  ' Comedy',
  ' Adventure',
  ' Thriller'],
 'keywords': ['outlaw',
  ' based on video game',
  ' unlikely friendship',
  ' talking robot',
  ' missing girl',
  ' band of misfits',
  ' mysterious power'],
 'release_date': '2024-08-07',
 'director': ['Eli Roth'],
 'director_popularity': ['24.36'],
 'movie_popularity': 2388.352,
 'movie_imdb_id': 'tt4978420',
 'movie_imdb_rating': 4.5,
 'runtime_minutes': 101}

In [59]:
for key in first_it.keys():
    print(key,'->',type(first_it[key]))

id -> <class 'int'>
title -> <class 'str'>
overview -> <class 'str'>
genres -> <class 'list'>
keywords -> <class 'list'>
release_date -> <class 'str'>
director -> <class 'list'>
director_popularity -> <class 'list'>
movie_popularity -> <class 'float'>
movie_imdb_id -> <class 'str'>
movie_imdb_rating -> <class 'float'>
runtime_minutes -> <class 'int'>

In [60]:
# id: int
# title: str
# overview:str 
# genres: list
# keywords: list
# release_date: str
# director: list
# director_popularity:list
# movie_popularity:float
# movie_imdb_id:str 
# movie_imdb_rating:float
# runtime_minutes:int

In [69]:
movie_docs = list(movies_documents.values())

In [71]:
movie_docs[:4]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'runtime_minutes': 128},
 {'id': 917496,
  'title': 'Beetlejuice Beetlejuice',
  'overview': "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
  'genres': ['Comedy', ' Horror', ' Fantasy'],
  'keywords': ['afterlife',
   ' haunted house',
   ' sequel',
   ' paranormal',
   ' teenage girl',
   ' gothic',
   ' death',
   ' new england',
   ' ghost',
   ' horror comedy',
   ' unexpected death',
   ' mother daughter relationship',
   ' fantasy',
   ' fantasy comedy'],
  'release_date': '2024-09-04',
  'director': ['Tim Burton'],
  'director_popularity': ['33.964'],
  'movie_popularity': 1567.733,
  'movie_imdb_id': 'tt2049403',
  'movie_imdb_rating': 7.1,
  'runtime_minutes': 105},
 {'id': 1022789,
  'title': 'Inside Out 2',
  'overview': "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  'genres': ['Animation', ' Family', ' Adventure', ' Comedy'],
  'keywords': ['sadness',
   ' disgust',
   ' sequel',
   ' computer animation',
   ' teenage girl',
   ' fear',
   ' anger',
   ' envy',
   ' aftercreditsstinger',
   ' duringcreditsstinger',
   ' emotions',
   ' embarrasment',
   ' anxious',
   ' joy',
   ' anxiety',
   ' frustrated'],
  'release_date': '2024-06-11',
  'director': ['Kelsey Mann'],
  'director_popularity': ['13.717'],
  'movie_popularity': 1485.085,
  'movie_imdb_id': 'tt22022452',
  'movie_imdb_rating': 7.7,
  'runtime_minutes': 96}]

In [ ]:
res.json()

In [77]:
movies_docs = json.dumps(movie_docs)

In [79]:
movies_data = json.loads(movies_docs)

In [80]:
type(movies_data)

list

In [82]:
movies_data[:2]

[{'id': 365177,
  'title': 'Borderlands',
  'overview': 'Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.',
  'genres': ['Action',
   ' Science Fiction',
   ' Comedy',
   ' Adventure',
   ' Thriller'],
  'keywords': ['outlaw',
   ' based on video game',
   ' unlikely friendship',
   ' talking robot',
   ' missing girl',
   ' band of misfits',
   ' mysterious power'],
  'release_date': '2024-08-07',
  'director': ['Eli Roth'],
  'director_popularity': ['24.36'],
  'movie_popularity': 2388.352,
  'movie_imdb_id': 'tt4978420',
  'movie_imdb_rating': 4.5,
  'runtime_minutes': 101},
 {'id': 533535,
  'title': 'Deadpool & Wolverine',
  'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
  'genres': ['Action', ' Comedy', ' Science Fiction'],
  'keywords': ['hero',
   ' superhero',
   ' anti hero',
   ' mutant',
   ' breaking the fourth wall',
   ' marvel cinematic universe (mcu)',
   ' mutants',
   ' superhero teamup'],
  'release_date': '2024-07-24',
  'director': ['Shawn Levy'],
  'director_popularity': ['19.518'],
  'movie_popularity': 2433.46,
  'movie_imdb_id': 'tt6263850',
  'movie_imdb_rating': 8.0,
  'runtime_minutes': 128}]

In [85]:
mov_df = pd.DataFrame().from_dict(movies_data)

In [90]:
mov_df['overview'].fillna('-',inplace=True)

In [93]:
mov_df['release_date'].fillna('-',inplace=True)

In [94]:
mov_df.isnull().sum()

id                     0
title                  0
overview               0
genres                 0
keywords               0
release_date           0
director               0
director_popularity    0
movie_popularity       0
movie_imdb_id          0
movie_imdb_rating      0
runtime_minutes        0
dtype: int64

In [99]:
movies_data = list(mov_df.T.to_dict().values())

In [121]:
res = requests.post(url='http://localhost:8000/data',json={'movies':movies_data})

In [122]:
res.json()

{'acknowledged': True,

## Retrieving Data

In [7]:
res = requests.get(url='http://localhost:8080/get/all')

In [8]:
res.status_code

200

In [9]:
res.json()[0].keys()

dict_keys(['id', 'title', 'overview', 'genres', 'keywords', 'release_date', 'director', 'director_popularity', 'movie_popularity', 'movie_imdb_id', 'movie_imdb_rating', 'runtime_minutes'])

In [10]:
df = pd.DataFrame().from_dict(res.json())

# Data Preprocessing

In [11]:
df.head()

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,runtime_minutes
0,365177,Borderlands,"Returning to her home planet, an infamous boun...","[Action, Science Fiction, Comedy, Adventure...","[outlaw, based on video game, unlikely frien...",2024-08-07,[Eli Roth],[24.36],2388.352,tt4978420,4.5,101
1,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,"[Action, Comedy, Science Fiction]","[hero, superhero, anti hero, mutant, break...",2024-07-24,[Shawn Levy],[19.518],2433.460,tt6263850,8.0,128
2,917496,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...","[Comedy, Horror, Fantasy]","[afterlife, haunted house, sequel, paranorm...",2024-09-04,[Tim Burton],[33.964],1567.733,tt2049403,7.1,105
3,1022789,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,"[Animation, Family, Adventure, Comedy]","[sadness, disgust, sequel, computer animati...",2024-06-11,[Kelsey Mann],[13.717],1485.085,tt22022452,7.7,96
4,970347,The Killer,"Zee is a feared contract killer known as ""the ...","[Action, Thriller, Crime]",[],2024-08-22,[John Woo],[16.765],1084.443,tt1121948,5.7,126

In [12]:
df['release_date'].replace({'-':np.nan},inplace=True)

In [13]:
df['startYear'] = pd.to_datetime(df['release_date']).dt.year

# Building Models

In [14]:
tokenizer = nltk.RegexpTokenizer(r"[^\W+\d+]+")

In [15]:
with open('../datasets/stopwords.txt','r') as stopfp:
    stop_words = stopfp.readlines()

In [16]:
stop_words = stop_words[0].replace('"','').split(', ')

In [17]:
stop_words

['0o',
 '0s',
 '3a',
 '3b',
 '3d',
 '6b',
 '6o',
 'a',
 'a1',
 'a2',
 'a3',
 'a4',
 'ab',
 'able',
 'about',
 'above',
 'abst',
 'ac',
 'accordance',
 'according',
 'accordingly',
 'across',
 'act',
 'actually',
 'ad',
 'added',
 'adj',
 'ae',
 'af',
 'affected',
 'affecting',
 'affects',
 'after',
 'afterwards',
 'ag',
 'again',
 'against',
 'ah',
 'ain',
 "ain't",
 'aj',
 'al',
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'announce',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'ao',
 'ap',
 'apart',
 'apparently',
 'appear',
 'appreciate',
 'appropriate',
 'approximately',
 'ar',
 'are',
 'aren',
 'arent',
 "aren't",
 'arise',
 'around',
 'as',
 "a's",
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'au',
 'auth',
 'av',
 'available',
 'aw',
 'away',
 'awfully',
 'ax',
 'ay',
 'az',
 'b',
 'b1',
 'b2',
 'b3',
 'ba',
 'back',
 'bc',
 'bd',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'begin',
 'beginning',
 'beginnings',
 'begins',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'bi',
 'bill',
 'biol',
 'bj',
 'bk',
 'bl',
 'bn',
 'both',
 'bottom',
 'bp',
 'br',
 'brief',
 'briefly',
 'bs',
 'bt',
 'bu',
 'but',
 'bx',
 'by',
 'c',
 'c1',
 'c2',
 'c3',
 'ca',
 'call',
 'came',
 'can',
 'cannot',
 'cant',
 "can't",
 'cause',
 'causes',
 'cc',
 'cd',
 'ce',
 'certain',
 'certainly',
 'cf',
 'cg',
 'ch',
 'changes',
 'ci',
 'cit',
 'cj',
 'cl',
 'clearly',
 'cm',
 "c'mon",
 'cn',
 'co',
 'com',
 'come',
 'comes',
 'con',
 'concerning',
 'consequently',
 'consider',
 'considering',
 'contain',
 'containing',
 'contains',
 'corresponding',
 'could',
 'couldn',
 'couldnt',
 "couldn't",
 'course',
 'cp',
 'cq',
 'cr',
 'cry',
 'cs',
 "c's",
 'ct',
 'cu',
 'currently',
 'cv',
 'cx',
 'cy',
 'cz',
 'd',
 'd2',
 'da',
 'date',
 'dc',
 'dd',
 'de',
 'definitely',
 'describe',
 'described',
 'despite',
 'detail',
 'df',
 'di',
 'did',
 'didn',
 "didn't",
 'different',
 'dj',
 'dk',
 'dl',
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 'done',
 "don't",
 'down',
 'downwards',
 'dp',
 'dr',
 'ds',
 'dt',
 'du',
 'due',
 'during',
 'dx',
 'dy',
 'e',
 'e2',
 'e3',
 'ea',
 'each',
 'ec',
 'ed',
 'edu',
 'ee',
 'ef',
 'effect',
 'eg',
 'ei',
 'eight',
 'eighty',
 'either',
 'ej',
 'el',
 'eleven',
 'else',
 'elsewhere',
 'em',
 'empty',
 'en',
 'end',
 'ending',
 'enough',
 'entirely',
 'eo',
 'ep',
 'eq',
 'er',
 'es',
 'especially',
 'est',
 'et',
 'et-al',
 'etc',
 'eu',
 'ev',
 'even',
 'ever',
 'every',
 'everybody',
 'everyone',
 'everything',
 'everywhere',
 'ex',
 'exactly',
 'example',
 'except',
 'ey',
 'f',
 'f2',
 'fa',
 'far',
 'fc',
 'few',
 'ff',
 'fi',
 'fifteen',
 'fifth',
 'fify',
 'fill',
 'find',
 'fire',
 'first',
 'five',
 'fix',
 'fj',
 'fl',
 'fn',
 'fo',
 'followed',
 'following',
 'follows',
 'for',
 'former',
 'formerly',
 'forth',
 'forty',
 'found',
 'four',
 'fr',
 'from',
 'front',
 'fs',
 'ft',
 'fu',
 'full',
 'further',
 'furthermore',
 'fy',
 'g',
 'ga',
 'gave',
 'ge',
 'get',
 'gets',
 'getting',
 'gi',
 'give',
 'given',
 'gives',
 'giving',
 'gj',
 'gl',
 'go',
 'goes',
 'going',
 'gone',
 'got',
 'gotten',
 'gr',
 'greetings',
 'gs',
 'gy',
 'h',
 'h2',
 'h3',
 'had',
 'hadn',
 "hadn't",
 'happens',
 'hardly',
 'has',
 'hasn',
 'hasnt',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'hed',
 "he'd",
 "he'll",
 'hello',
 'help',
 'hence',
 'her',
 'here',
 'hereafter',
 'hereby',
 'herein',
 'heres',
 "here's",
 'hereupon',
 'hers',
 'herself',
 'hes',
 "he's",
 'hh',
 'hi',
 'hid',
 'him',
 'himself',
 'his',
 'hither',
 'hj',
 'ho',
 'home',
 'hopefully',
 'how',
 'howbeit',
 'however',
 "how's",
 'hr',
 'hs',
 'http',
 'hu',
 'hundred',
 'hy',
 'i',
 'i2',
 'i3',
 'i4',
 'i6',
 'i7',
 'i8',
 'ia',
 'ib',
 'ibid',
 'ic',
 'id',
 "i'd",
 'ie',
 'if',
 'ig',
 'ignored',
 'ih',
 'ii',
 'ij',
 'il',
 "i'll",
 'im',
 "i'm",
 'immediate',
 'immediately',
 'importance',
 'important',
 'in',
 'inasmuch',
 'inc',
 'indeed',
 'index',
 'indicate',
 'indicated',
 'indicates',
 'information',
 'inner',
 'insofar',
 'instead',
 'interest',
 'into',
 'invention',
 'inward',
 'io',
 'ip',
 'iq',
 'ir',
 'is',
 'isn',
 "isn't",
 'it',
 'itd',
 "it'd",
 "it'll",
 'its',
 "it's",
 'itself',
 'iv',
 "i've",
 'ix',
 'iy',
 'iz',
 'j',
 'jj',
 'jr',
 'js',
 'jt',
 'ju',
 'just',
 'k',
 'ke',
 'keep',
 'keeps',
 'kept',
 'kg',
 'kj',
 'km',
 'know',
 'known',
 'knows',
 'ko',
 'l',
 'l2',
 'la',
 'largely',
 'last',
 'lately',
 'later',
 'latter',
 'latterly',
 'lb',
 'lc',
 'le',
 'least',
 'les',
 'less',
 'lest',
 'let',
 'lets',
 "let's",
 'lf',
 'like',
 'liked',
 'likely',
 'line',
 'little',
 'lj',
 'll',
 'll',
 'ln',
 'lo',
 'look',
 'looking',
 'looks',
 'los',
 'lr',
 'ls',
 'lt',
 'ltd',
 'm',
 'm2',
 'ma',
 'made',
 'mainly',
 'make',
 'makes',
 'many',
 'may',
 'maybe',
 'me',
 'mean',
 'means',
 'meantime',
 'meanwhile',
 'merely',
 'mg',
 'might',
 'mightn',
 "mightn't",
 'mill',
 'million',
 'mine',
 'miss',
 'ml',
 'mn',
 'mo',
 'more',
 'moreover',
 'most',
 'mostly',
 'move',
 'mr',
 'mrs',
 'ms',
 'mt',
 'mu',
 'much',
 'mug',
 'must',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'n',
 'n2',
 'na',
 'name',
 'namely',
 'nay',
 'nc',
 'nd',
 'ne',
 'near',
 'nearly',
 'necessarily',
 'necessary',
 'need',
 'needn',
 "needn't",
 'needs',
 'neither',
 'never',
 'nevertheless',
 'new',
 'next',
 'ng',
 'ni',
 'nine',
 'ninety',
 'nj',
 'nl',
 'nn',
 'no',
 'nobody',
 'non',
 'none',
 'nonetheless',
 'noone',
 'nor',
 'normally',
 'nos',
 'not',
 'noted',
 'nothing',
 'novel',
 'now',
 'nowhere',
 'nr',
 'ns',
 'nt',
 'ny',
 'o',
 'oa',
 'ob',
 'obtain',
 'obtained',
 'obviously',
 'oc',
 'od',
 'of',
 'off',
 'often',
 'og',
 'oh',
 'oi',
 'oj',
 'ok',
 'okay',
 'ol',
 'old',
 'om',
 'omitted',
 'on',
 'once',
 'one',
 'ones',
 'only',
 'onto',
 'oo',
 'op',
 'oq',
 'or',
 'ord',
 'os',
 'ot',
 'other',
 'others',
 'otherwise',
 'ou',
 'ought',
 'our',
 'ours',
 'ourselves',
 'out',
 'outside',
 'over',
 'overall',
 'ow',
 'owing',
 'own',
 'ox',
 'oz',
 'p',
 'p1',
 'p2',
 'p3',
 'page',
 'pagecount',
 'pages',
 'par',
 'part',
 'particular',
 'particularly',
 'pas',
 'past',
 'pc',
 'pd',
 'pe',
 'per',
 'perhaps',
 'pf',
 'ph',
 'pi',
 'pj',
 'pk',
 'pl',
 'placed',
 'please',
 'plus',
 'pm',
 'pn',
 'po',
 'poorly',
 'possible',
 'possibly',
 'potentially',
 'pp',
 'pq',
 'pr',
 'predominantly',
 'present',
 'presumably',
 'previously',
 'primarily',
 'probably',
 'promptly',
 'proud',
 'provides',
 'ps',
 'pt',
 'pu',
 'put',
 'py',
 'q',
 'qj',
 'qu',
 'que',
 'quickly',
 'quite',
 'qv',
 'r',
 'r2',
 'ra',
 'ran',
 'rather',
 'rc',
 'rd',
 're',
 'readily',
 'really',
 'reasonably',
 'recent',
 'recently',
 'ref',
 'refs',
 'regarding',
 'regardless',
 'regards',
 'related',
 'relatively',
 'research',
 'research-articl',
 'respectively',
 'resulted',
 'resulting',
 'results',
 'rf',
 'rh',
 'ri',
 'right',
 'rj',
 'rl',
 'rm',
 'rn',
 'ro',
 'rq',
 'rr',
 'rs',
 'rt',
 'ru',
 'run',
 'rv',
 'ry',
 's',
 's2',
 'sa',
 'said',
 'same',
 'saw',
 'say',
 'saying',
 'says',
 'sc',
 'sd',
 'se',
 'sec',
 'second',
 'secondly',
 'section',
 'see',
 'seeing',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'seen',
 'self',
 'selves',
 'sensible',
 'sent',
 'serious',
 'seriously',
 'seven',
 'several',
 'sf',
 'shall',
 'shan',
 "shan't",
 'she',
 'shed',
 "she'd",
 "she'll",
 'shes',
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'show',
 'showed',
 'shown',
 'showns',
 'shows',
 'si',
 'side',
 'significant',
 'significantly',
 'similar',
 'similarly',
 'since',
 'sincere',
 'six',
 'sixty',
 'sj',
 'sl',
 'slightly',
 'sm',
 'sn',
 'so',
 'some',
 'somebody',
 'somehow',
 'someone',
 'somethan',
 'something',
 'sometime',
 'sometimes',
 'somewhat',
 'somewhere',
 'soon',
 'sorry',
 'sp',
 'specifically',
 'specified',
 'specify',
 'specifying',
 'sq',
 'sr',
 'ss',
 'st',
 'still',
 'stop',
 'strongly',
 'sub',
 'substantially',
 'successfully',
 'such',
 'sufficiently',
 'suggest',
 'sup',
 'sure',
 'sy',
 'system',
 'sz',
 't',
 't1',
 't2',
 't3',
 'take',
 'taken',
 'taking',
 'tb',
 'tc',
 'td',
 'te',
 'tell',
 'ten',
 'tends',
 'tf',
 'th',
 'than',
 'thank',
 'thanks',
 'thanx',
 'that',
 "that'll",
 'thats',
 "that's",
 "that've",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 'thereafter',
 'thereby',
 'thered',
 'therefore',
 'therein',
 "there'll",
 'thereof',
 'therere',
 'theres',
 "there's",
 'thereto',
 'thereupon',
 "there've",
 'these',
 'they',
 'theyd',
 "they'd",
 "they'll",
 'theyre',
 "they're",
 "they've",
 'thickv',
 'thin',
 'think',
 'third',
 'this',
 'thorough',
 'thoroughly',
 'those',
 'thou',
 'though',
 'thoughh',
 'thousand',
 'three',
 'throug',
 'through',
 'throughout',
 'thru',
 'thus',
 'ti',
 'til',
 'tip',
 'tj',
 'tl',
 'tm',
 'tn',
 'to',
 'together',
 'too',
 'took',
 'top',
 'toward',
 'towards',
 'tp',
 'tq',
 'tr',
 'tried',
 'tries',
 'truly',
 'try',
 'trying',
 'ts',
 "t's",
 'tt',
 'tv',
 'twelve',
 'twenty',
 'twice',
 'two',
 'tx',
 'u',
 'u201d',
 'ue',
 'ui',
 'uj',
 'uk',
 ...]

> #### after downloading it from `> spacy download en_core_web_lg` command

In [18]:
nlp = spacy.load('en_core_web_lg')

In [19]:
s1 = nlp(u'Drama Romance murder Action superhero Marvel')
s2 = nlp(u'Action Drama Crime superhero Space Spiderman')
s3 = nlp(u'Mystery Romance Thriller Action Science Fiction Spiderman')

In [20]:
s4 = nlp(u'')
s4 = s4.from_docs([s1,s2,s3])

In [21]:
s4

Drama Romance murder Action superhero Marvel Action Drama Crime superhero Space Spiderman Mystery Romance Thriller Action Science Fiction Spiderman

In [22]:
df = df[~df['movie_imdb_id'].duplicated()].reset_index().drop(columns = 'index')

In [23]:
# genres tags
genre_tags = df['genres'].apply(lambda x: ' '.join(x).strip().lower()).to_list()

In [24]:
genre_tags[:5]

['action  science fiction  comedy  adventure  thriller',
 'action  comedy  science fiction',
 'comedy  horror  fantasy',
 'animation  family  adventure  comedy',
 'action  thriller  crime']

In [25]:
# keywords tags 
keyword_tags = df['keywords'].apply(lambda x: ' '.join(x).strip().lower()).to_list()

In [26]:
keyword_tags[:5]

['outlaw  based on video game  unlikely friendship  talking robot  missing girl  band of misfits  mysterious power',
 'hero  superhero  anti hero  mutant  breaking the fourth wall  marvel cinematic universe (mcu)  mutants  superhero teamup',
 'afterlife  haunted house  sequel  paranormal  teenage girl  gothic  death  new england  ghost  horror comedy  unexpected death  mother daughter relationship  fantasy  fantasy comedy',
 'sadness  disgust  sequel  computer animation  teenage girl  fear  anger  envy  aftercreditsstinger  duringcreditsstinger  emotions  embarrasment  anxious  joy  anxiety  frustrated',
 '']

In [27]:
overviews = df['overview']

In [28]:
# overview tags
overview_tags = []
for overview in tqdm(overviews):
    tags = []
    new_overview = ' '.join(set(tokenizer.tokenize(overview.lower())))
    word_token = word_tokenize(new_overview)
    for w in word_token:
        if (w.lower() not in stop_words):
            tags.append(w.strip())
    overview_tags.append(' '.join(tags).lower())

100%|████████████████████████████████████████████████████████████████████████████| 9509/9509 [00:07<00:00, 1345.01it/s]

In [29]:
overview_tags[:6]

['bandits dangerous bounty girl alliance battle power unexpected heroes monsters protect infamous young returning team unimaginable key forms planet holds hunter',
 'threat homeworld existential days faces wolverine life wilson mercenary suit civilian reluctant listless wade flexible deadpool reluctantly morally toils',
 'upside daughter generations deetz winter astrid teenage life haunted river lydia opens afterlife turned beetlejuice family portal accidentally tragedy return',
 'sudden teenager feel riley fear joy emotions disgust mind unexpected headquarters undergoing anger operation anxiety running sadness demolition accounts room successful long',
 'woman refuses hunted determined colleagues contract queen murder zee finds criminal blind detective police young dead feared killer',
 'youth friends villain shin battles kwun leadership chaos kowloon life invasion troubled safe series lok city enters lessons walled fierce cyclone protect vow order amidst master big set resist discovers twelfth chan learns accidentally close']

In [30]:
df.columns

Index(['id', 'title', 'overview', 'genres', 'keywords', 'release_date',
       'director', 'director_popularity', 'movie_popularity', 'movie_imdb_id',
       'movie_imdb_rating', 'runtime_minutes', 'startYear'],
      dtype='object')

In [34]:
genre_doc = []
keyword_doc = []
overview_doc = []
for i in tqdm(df.index):
    genre_doc.append(nlp(f'{genre_tags[i]}'))
    keyword_doc.append(nlp(f'{keyword_tags[i]}'))
    overview_doc.append(nlp(f'{overview_tags[i]}'))

100%|██████████████████████████████████████████████████████████████████████████████| 9509/9509 [03:06<00:00, 50.94it/s]

In [36]:
df['genre_doc'] = genre_doc
df['keyword_doc'] = keyword_doc
df['overview_doc'] = overview_doc

In [37]:
tags = []
for i in tqdm(df.index):
    tag = nlp('').from_docs([genre_doc[i], keyword_doc[i], overview_doc[i]])
    tags.append(tag)

100%|████████████████████████████████████████████████████████████████████████████| 9509/9509 [00:03<00:00, 2919.43it/s]

In [38]:
df['tags'] = tags

In [ ]:
ft_tags

In [ ]:
df.query(f"movie_imdb_id == 'tt22022452'")

In [ ]:

df.sort_values(by='movie_popularity',ascending=False).head(20)

In [40]:
def search_movie(word):
    results = []
    for i,movie_title in enumerate(df['title']):
        if movie_title.__contains__(word):
            results.append(i)
    return df.iloc[results]

In [123]:
search_movie('Furious')

,id,title,overview,genres,keywords,release_date,director,director_popularity,movie_popularity,movie_imdb_id,movie_imdb_rating,runtime_minutes,startYear,genre_doc,keyword_doc,overview_doc,tags
239,384018,Fast & Furious Presents: Hobbs & Shaw,Ever since US Diplomatic Security Service Agen...,"[Action, Adventure, Comedy]","[london, england, biological weapon, secret...",2019-08-01,[David Leitch],[11.198],81.463,tt6806448,6.5,137,2019.0,"(action, , adventure, , comedy)","(london, , england, , biological, weapon, ,...","(body, agent, ruthless, future, shaw, traded, ...","(action, , adventure, , comedy, london, , e..."
349,168259,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,"[Action, Thriller, Crime]","[car race, speed, street race, revenge, ra...",2015-04-01,[James Wan],[8.496],79.822,tt2820852,7.1,137,2015.0,"(action, , thriller, , crime)","(car, race, , speed, , street, race, , reve...","(seeks, toretto, comatose, deckard, family, sh...","(action, , thriller, , crime, car, race, , ..."
648,337339,The Fate of the Furious,When a mysterious woman seduces Dom into the w...,"[Action, Crime, Thriller]","[new york city, submarine, rescue mission, ...",2017-04-12,[F. Gary Gray],[3.614],58.750,tt4630562,6.6,136,2017.0,"(action, , crime, , thriller)","(new, york, city, , submarine, , rescue, mis...","(trials, closest, woman, face, dom, test, betr...","(action, , crime, , thriller, new, york, cit..."
2044,15854,Kung Fu Panda: Secrets of the Furious Five,Ordered to teach a martial arts class of rambu...,"[Animation, Family, Action]","[martial arts, kung fu, panda, anthropomorp...",2008-11-08,[Raman Hui],[3.489],33.485,tt1287845,7.0,25,2008.0,"(animation, , family, , action)","(martial, arts, , kung, fu, , panda, , anth...","(pasts, teach, kittens, tells, class, arts, or...","(animation, , family, , action, martial, art..."

## Spacy Model Recommedations

In [ ]:
imdb_id = 'tt0119282'
df.query(f"movie_imdb_id == '{imdb_id}'")

In [112]:
def recommendations_for(imdb_id, year = 2000, freq = 10):
    mv_df = df.query(f'startYear >= {year} & movie_imdb_rating >= 5.0').reset_index().drop(columns = 'index')
    movie =  mv_df.query(f"movie_imdb_id == '{imdb_id}'")
    title = movie.title.values[0]
    year = movie.startYear.values[0]
    scores = []
    indices = range(mv_df.shape[0])
    
    print(f"Best recommendation for `{title} {int(year)}` is:")
    movie_tags = mv_df.query(f"movie_imdb_id == '{imdb_id}'")['tags'].values[0]
    
    for index in indices:
        scores.append(np.round(np.ceil(movie_tags.similarity(mv_df.iloc[index].tags) * 1000) / 1000,2))
        
    recommends = pd.DataFrame({'imdb_id':mv_df.movie_imdb_id.values,
                               'title':mv_df.title.values,
                               'startYear':mv_df.startYear.values,
                               'rating':mv_df.movie_imdb_rating,
                               'score':scores,
                               'popularity':mv_df.movie_popularity,
                               'rate_pop':(mv_df.movie_popularity / 1000) * mv_df.movie_imdb_rating
                                })
    
    recommends.drop(recommends.query('score >= 1.0').index,inplace = True)
    recommends = recommends.sort_values(by=['score','rate_pop','startYear'],ascending = False).reset_index().drop(columns = ['index','rate_pop'])
    return recommends.head(freq)

In [124]:
recommendations_for('tt4630562',freq=30)

Best recommendation for `The Fate of the Furious 2017` is:

,imdb_id,title,startYear,rating,score,popularity
0,tt1345836,The Dark Knight Rises,2012.0,8.4,0.90,68.513
1,tt1136617,The Killer,2023.0,6.7,0.90,31.075
2,tt3522806,Mechanic: Resurrection,2016.0,5.7,0.90,33.443
3,tt2377322,Deliver Us from Evil,2014.0,6.2,0.89,32.077
4,tt2101341,Dead Man Down,2013.0,6.4,0.89,18.952
5,tt0417148,Snakes on a Plane,2006.0,5.5,0.89,20.947
6,tt11671006,The Man from Toronto,2022.0,5.8,0.89,19.165
7,tt19319352,Mayhem!,2023.0,6.3,0.88,326.320
8,tt0455944,The Equalizer,2014.0,7.2,0.88,107.573
9,tt8589698,Teenage Mutant Ninja Turtles: Mutant Mayhem,2023.0,7.2,0.88,70.201
10,tt0186151,Frequency,2000.0,7.4,0.88,43.308
11,tt1129442,Transporter 3,2008.0,6.1,0.88,36.676
12,tt3110958,Now You See Me 2,2016.0,6.4,0.88,33.684
13,tt0945513,Source Code,2011.0,7.5,0.88,26.732
14,tt1999167,Naruto Shippuden the Movie: Blood Prison,2011.0,7.1,0.88,27.409
15,tt10342730,Spiral: From the Book of Saw,2021.0,5.2,0.88,36.962
16,tt27004149,Borderless Fog,2024.0,5.2,0.88,34.948
17,tt5719748,Cold Pursuit,2019.0,6.2,0.88,27.301
18,tt2005374,The Frozen Ground,2013.0,6.4,0.88,23.620
19,tt7390646,Black and Blue,2019.0,6.4,0.88,21.833
20,tt0281190,Shottas,2002.0,6.1,0.88,19.905
21,tt0295178,Austin Powers in Goldmember,2002.0,6.2,0.88,19.502
22,tt9597838,Shock Wave 2,2020.0,6.6,0.88,17.136
23,tt10283270,Detective vs. Sleuths,2022.0,6.2,0.88,17.904
24,tt8688634,21 Bridges,2019.0,6.6,0.88,16.566
25,tt4136456,The Virtuoso,2021.0,5.0,0.88,20.639
26,tt0387055,Battle in Heaven,2005.0,5.5,0.88,17.957
27,tt2078552,Blood,2012.0,6.0,0.88,16.130
28,tt1014801,Pistol Whipped,2008.0,5.0,0.88,17.468
29,tt0233469,Collateral Damage,2002.0,5.5,0.88,15.705

## FastText Model Recommendations

In [302]:
ft_nlp

'Spider-Man'

In [ ]:
def recommendations_for(imdb_id, year = 2000, freq = 10):
    mv_df = df.query(f'startYear >= {year}').reset_index().drop(columns = 'index')
    title = mv_df.query(f"movie_imdb_id == 'tt{imdb_id}'").title.values[0]
    scores = []
    indices = range(mv_df.shape[0])
    
    print(f"Best recommendation for `{title}` is:")
    movie_tags = nlp(mv_df.query(f"movie_imdb_id == 'tt{imdb_id}'")['tags'].values[0])
    
    for index in tqdm(indices):
        scores.append(np.floor(movie_tags.similarity(nlp(mv_df.iloc[index].tags)) * 100) / 100)
        
    recommends = pd.DataFrame({'imdb_id':mv_df.movie_imdb_id.values,
                               'title':mv_df.title.values,
                               'startYear':mv_df.startYear.values,
                               'rating':mv_df.movie_imdb_rating,
                               'score':scores,
                               'popularity':mv_df.movie_popularity,
                               'rate_pop':(mv_df.movie_popularity / 1000) * mv_df.movie_imdb_rating
                                })
    
    recommends.drop(recommends.query('score >= 1.0').index[0],inplace = True)
    recommends = recommends.sort_values(by=['score','rating','startYear'],ascending = False).reset_index().drop(columns = ['index','rate_pop'])
    return recommends.head(freq)